export enum ErrorType {
    PROVIDER_ERROR = "PROVIDER-ERROR",
    INTEGRATION_ERROR = "INTEGRATION-ERROR",
    ITEM_ERROR = "ITEM-ERROR",
    BPP_ERROR = "BPP-ERROR"
}

export interface ErrorDetail {
    message: string;
    type: ErrorType;
}

export const catalogRejectionErrors: Record<string, ErrorDetail> = {
    "90001": { message: "Fulfilment rate below declared standards", type: ErrorType.PROVIDER_ERROR },
    "90002": { message: "On-time delivery rate below declared standards", type: ErrorType.PROVIDER_ERROR },
    "90003": { message: "Select call failure more than published threshold", type: ErrorType.PROVIDER_ERROR },
    "90004": { message: "Init call failure more than published threshold", type: ErrorType.PROVIDER_ERROR },
    "90005": { message: "Confirm call failure more than published threshold", type: ErrorType.PROVIDER_ERROR },
    "90006": { message: "Percentage of customer issues resolved within resolution TATs is below published standards", type: ErrorType.PROVIDER_ERROR },
    "90007": { message: "Duplicate Store", type: ErrorType.PROVIDER_ERROR },
    "90008": { message: "Customer complaints more than published standards", type: ErrorType.PROVIDER_ERROR },
    "90009": { message: "Rejected store due to Item level rejection above threshold", type: ErrorType.PROVIDER_ERROR },
    "90010": { message: "Missing authorisation from NP", type: ErrorType.INTEGRATION_ERROR },
    "90011": { message: "Merchant status sent by Seller NP is unavailable", type: ErrorType.PROVIDER_ERROR },
    "90012": { message: "Country of Origin not present (For Packaged Products)", type: ErrorType.PROVIDER_ERROR },
    "90013": { message: "Only Hyperlocal Delivery allowed", type: ErrorType.PROVIDER_ERROR },
    "90014": { message: "Invalid Latitude", type: ErrorType.PROVIDER_ERROR },
    "90015": { message: "Invalid Longitude", type: ErrorType.PROVIDER_ERROR },
    "90016": { message: "Invalid customisation group data", type: ErrorType.PROVIDER_ERROR },
    "90017": { message: "Stores less than declared threshold", type: ErrorType.PROVIDER_ERROR },
    "90018": { message: "Empty Address field", type: ErrorType.PROVIDER_ERROR },
    "90019": { message: "Other Provider Error", type: ErrorType.PROVIDER_ERROR },
    "90020": { message: "Tags type not present against items", type: ErrorType.PROVIDER_ERROR },
    "90021": { message: "Invalid Address received", type: ErrorType.PROVIDER_ERROR },
    "90022": { message: "Invalid city received", type: ErrorType.PROVIDER_ERROR },
    "90023": { message: "Invalid contact number- not 10 digit", type: ErrorType.PROVIDER_ERROR },
    "90024": { message: "Invalid FSSAI", type: ErrorType.PROVIDER_ERROR },
    "90025": { message: "Delivery radius not given", type: ErrorType.PROVIDER_ERROR },
    "90026": { message: "Store timing not in correct format", type: ErrorType.PROVIDER_ERROR },
    "90027": { message: "Locality & city mismatch", type: ErrorType.PROVIDER_ERROR },
    "90028": { message: "Store not received on search for 2 consecutive days", type: ErrorType.PROVIDER_ERROR },
    "90029": { message: "Store disabled by Seller App", type: ErrorType.PROVIDER_ERROR },
    "90030": { message: "Store Category mapping sent empty or unavailable at Buyer App side", type: ErrorType.PROVIDER_ERROR },
    "90031": { message: "NP integration version mis-match", type: ErrorType.INTEGRATION_ERROR },
    "90032": { message: "Store location error", type: ErrorType.PROVIDER_ERROR },
    "90033": { message: "Provider in Blacklisted", type: ErrorType.PROVIDER_ERROR },
    "91001": { message: "Item price > MRP", type: ErrorType.ITEM_ERROR },
    "91002": { message: "Use of restrictive keywords", type: ErrorType.ITEM_ERROR },
    "91003": { message: "No Images found", type: ErrorType.ITEM_ERROR },
    "91004": { message: "Duplicate Images Found", type: ErrorType.ITEM_ERROR },
    "91005": { message: "Low quality Image Found", type: ErrorType.ITEM_ERROR },
    "91006": { message: "Image Title Mismatch", type: ErrorType.ITEM_ERROR },
    "91007": { message: "Other Mandatory/Statutory Field not there", type: ErrorType.ITEM_ERROR },
    "91008": { message: "Duplicate Product", type: ErrorType.ITEM_ERROR },
    "91010": { message: "Price is Zero", type: ErrorType.ITEM_ERROR },
    "91011": { message: "Incorrect Image File Format", type: ErrorType.ITEM_ERROR },
    "91012": { message: "Country of Origin not present (For Packaged Products)", type: ErrorType.ITEM_ERROR },
    "91013": { message: "Net Quantity not present", type: ErrorType.ITEM_ERROR },
    "91014": { message: "FSSAI/Statutory requirement not present (For packaged products)", type: ErrorType.ITEM_ERROR },
    "91015": { message: "BIS Mark not present", type: ErrorType.ITEM_ERROR },
    "91016": { message: "Product miscategorized", type: ErrorType.ITEM_ERROR },
    "91017": { message: "Others - Add specific Error Description", type: ErrorType.ITEM_ERROR },
    "91018": { message: "Available quantity for the SKU is either absent or invalid", type: ErrorType.ITEM_ERROR },
    "91019": { message: "Category for the SKU does not exist", type: ErrorType.ITEM_ERROR },
    "91020": { message: "The parameters for customisation of SKU are not shared", type: ErrorType.ITEM_ERROR },
    "91021": { message: "Category field is missing", type: ErrorType.ITEM_ERROR },
    "91022": { message: "Customer care contact details missing", type: ErrorType.ITEM_ERROR },
    "91023": { message: "MRP less than zero", type: ErrorType.ITEM_ERROR },
    "91024": { message: "Price less than zero", type: ErrorType.ITEM_ERROR },
    "91025": { message: "Item status sent by Seller NP is unavailable", type: ErrorType.ITEM_ERROR },
    "91026": { message: "Invalid Item ID", type: ErrorType.ITEM_ERROR },
    "91027": { message: "Invalid Service Provider ID", type: ErrorType.ITEM_ERROR },
    "91028": { message: "Customisation not present", type: ErrorType.ITEM_ERROR },
    "91029": { message: "Invalid customisation group", type: ErrorType.ITEM_ERROR },
    "92001": { message: "NP integration version mis-match", type: ErrorType.BPP_ERROR },
    "92002": { message: "Missing authorisation from NP", type: ErrorType.BPP_ERROR },
    "92003": { message: "Mandatory field missing or the data format is incorrect for all Providers", type: ErrorType.BPP_ERROR },
    "92004": { message: "Invalid domain sent", type: ErrorType.BPP_ERROR },
    "92005": { message: "NP is blacklisted or inactive or not onboarded yet", type: ErrorType.BPP_ERROR },
    "92006": { message: "Provider Rejections crossed threshold in single transaction ID", type: ErrorType.BPP_ERROR }
};
