interface IGroceryJSON {
  [key: string]: { brand: boolean }
}
export const groceryJSON: IGroceryJSON = {
  'Fruits and Vegetables': { brand: true },
  'Masala & Seasoning': { brand: false },
  'Falseil & Ghee': { brand: false },
  'Eggs, Meat & Fish': { brand: false },
  'Cleaning & Household': { brand: false },
  'Bakery, Cakes & Dairy': { brand: false },
  'Pet Care': { brand: false },
  Stationery: { brand: false },
  'Dairy and Cheese': { brand: false },
  'Snacks, Dry Fruits, Nuts': { brand: false },
  'Pasta, Soup and Noodles': { brand: false },
  'Cereals and Breakfast': { brand: false },
  'Sauces, Spreads and Dips': { brand: false },
  'Chocolates and Biscuits': { brand: false },
  'Cooking and Baking Needs': { brand: false },
  'Tinned and Processed Food': { brand: false },
  'Atta, Flours and Sooji': { brand: false },
  'Rice and Rice Products': { brand: false },
  'Dals and Pulses': { brand: false },
  'Salt, Sugar and Jaggery': { brand: false },
  'Energy and Soft Drinks': { brand: false },
  Water: { brand: false },
  'Tea and Coffee': { brand: false },
  'Fruit Juices and Fruit Drinks': { brand: false },
  'Snacks and Namkeen': { brand: false },
  'Ready to Cook and Eat': { brand: false },
  'Pickles and Chutney': { brand: false },
  'Indian Sweets': { brand: false },
  'Frozen Vegetables': { brand: false },
  'Frozen Snacks': { brand: false },
  'Gift Voucher': { brand: false },
}
