export const SIZE = [
  '5-6 Years',
  'UK1',
  '30 mm',
  '40K',
  'UK7',
  '44DDD',
  '9-10 Years',
  '30E',
  '12',
  'IND-3',
  'UK2',
  '38C',
  '28',
  '48D',
  '48FF',
  '30C',
  'UK13',
  '42H',
  '50G',
  '44 Alterable',
  '30F',
  '18-24 Months',
  '34 mm',
  '44I',
  '52J',
  '46G',
  '42G',
  '20',
  '54DD',
  '12-18 Months',
  '54B',
  '34',
  '0-1 Years',
  '46DD',
  '48F',
  'UK1.5',
  '23',
  '46I',
  '50J',
  '52AA',
  '42 Alterable',
  '9XL',
  'XXS',
  '8-9 Years',
  '3-4 Years',
  '10-11 Years',
  '40A',
  '50',
  '46F',
  '34A',
  'IND-13',
  '46D',
  '52DD',
  '6-9 Months',
  '38A',
  '18 mm',
  '52C',
  '46',
  '48DD',
  '54F',
  '28D',
  'UK5',
  '40I',
  '30FF',
  '46E',
  '42I',
  '9',
  '42C',
  '16',
  '44DD',
  '28C',
  '48A',
  '54H',
  '40B',
  '34D',
  '38B',
  '54',
  '40DDD',
  'UK11.5',
  '32C',
  '44G',
  'L',
  '14',
  '1-2 Years',
  '11-12 Years',
  '44B',
  '48EE',
  '28E',
  'UK10.5',
  '48 Alterable',
  '46 Alterable',
  '52A',
  '40F',
  '39',
  '32E',
  'S',
  '48DDD',
  '44J',
  '36C',
  '40 Alterable',
  '54EE',
  '36B',
  '36E',
  '19',
  '46K',
  '32FF',
  '2-3 Years',
  '44A',
  '36D',
  '9-12 Months',
  '34FF',
  '46A',
  '42B',
  'UK9.5',
  '15-16 Years',
  'IND-2',
  '52E',
  '48H',
  'UK7.5',
  '44D',
  '50F',
  '44EE',
  '44E',
  'Unstitched',
  '8',
  '5XL',
  'UK13.5',
  '32D',
  '46 mm',
  '11',
  '40GG',
  '40J',
  '10XL',
  '22 mm',
  '52H',
  '46GG',
  '7-8 Years',
  '40H',
  'XXL',
  '6-12 Months',
  'UK12.5',
  '32B',
  '13-14 Years',
  'UK11',
  '28B',
  'IND-10',
  '22',
  'IND-4',
  '44C',
  '40E',
  '34B',
  '15',
  '50DD',
  '46EE',
  '50EE',
  '58',
  '48E',
  '42E',
  '32F',
  '50 Alterable',
  'UK3',
  '44F',
  '48AA',
  '48C',
  '32 Alterable',
  '54J',
  '52B',
  '25',
  '52D',
  '52EE',
  '40EE',
  '2XL',
  '32A',
  '8XL',
  '60 Alterable',
  '40C',
  '52',
  '14-15 Years',
  '52G',
  '17',
  '50FF',
  '32 mm',
  '40G',
  '13',
  'IND-11',
  '7',
  '34 Alterable',
  '30',
  '48B',
  'XL',
  '46FF',
  '40FF',
  '44 mm',
  '48G',
  '42J',
  '12-13 Years',
  '48GG',
  '50B',
  'XXXL',
  'IND-6',
  'UK5.5',
  '34E',
  '56 Alterable',
  '30B',
  '54D',
  '50C',
  '24',
  '24 mm',
  '6XL',
  '50D',
  'UK6',
  'UK6.5',
  '36 Alterable',
  'UK12',
  '54C',
  '54K',
  'IND-9',
  'Semi Stitched',
  '36A',
  '40DD',
  '28 Alterable',
  '50DDD',
  '28A',
  '26 Alterable',
  '46H',
  '42F',
  '44K',
  '40AA',
  '42K',
  '30DD',
  '48',
  '48I',
  '4XL',
  '50GG',
  '44',
  '32DD',
  '4-5 Years',
  '52K',
  '52F',
  '48K',
  'IND-12',
  '44FF',
  '42D',
  'IND-7',
  '40D',
  '60',
  '54I',
  '52I',
  'UK8.5',
  '42',
  '40',
  '54A',
  '3-6 Months',
  'M',
  '38D',
  '46B',
  '52FF',
  '38',
  '36',
  '32',
  'UK10',
  '3XL',
  '50A',
  '52GG',
  '48J',
  '50K',
  '34DD',
  '52DDD',
  '0-3 Months',
  '36 mm',
  '20 mm',
  '42GG',
  '40 mm',
  '21',
  '54DDD',
  'IND-5',
  '30D',
  '34F',
  '46AA',
  '42A',
  '50AA',
  'UK2.5',
  '54FF',
  '42 mm',
  '54AA',
  '34C',
  '44H',
  '46DDD',
  '46J',
  '30 Alterable',
  '10',
  'IND-8',
  '54 Alterable',
  '58 Alterable',
  '50H',
  '42EE',
  '54E',
  '26',
  '54GG',
  '42FF',
  'XS',
  '54G',
  'UK9',
  '7XL',
  '30A',
  '18',
  '0-6 Months',
  '6-7 Years',
  'Free Size',
  'UK4.5',
  '38 Alterable',
  '50I',
  'UK3.5',
  'UK8',
  '38E',
  '56',
  '44AA',
  '50E',
  'UK4',
  '44GG',
  '46C',
  '52 Alterable',
]
export const FOOTWEAR_TYPE = [
  'boat shoes',
  'brogues',
  'clogs',
  'comfort sandals',
  'derbys',
  'driving shoes',
  'espadrilles',
  'flat boots',
  'flatforms',
  'gladiators',
  'kolhapuri',
  'loafers',
  'mojaris',
  'monks',
  'oxfords',
  'skate shoes',
  'sliders',
  'slip-on sneakers',
  'sneakers',
  'thong flip-flops',
  'trekking shoes',
]
export const LENS_MATERIAL = ['alpha', 'composite', 'glass', 'plastic', 'polycarbonate', 'trivex', 'high index']
export const FRAME_TYPE = ['alpha', 'full rim', 'half rim', 'rimless']
export const SEASON = ['alpha', 'rainy', 'winter', 'summer', 'autumn', 'fall_winter']
export const SPORT_TYPE = [
  'alpha',
  'running',
  'walking',
  'basketball',
  'baseball',
  'football',
  'soccer',
  'hockey',
  'lacrosse',
  'rugby',
  'volleyball',
  'training',
  'golf',
  'tennis',
  'cycling',
  'skateboarding',
]
export const FASTEN_TYPE = [
  'alpha',
  'ankle loop',
  'backstrap',
  'buckle',
  'closed back',
  'lace-up',
  'no back strap',
  'open back',
  'slip-on',
  'velcro',
  'zip',
]
export const FABRIC = [
  'alpha',
  'acrylic',
  'art silk',
  'bamboo',
  'chambray',
  'chanderi cotton',
  'chanderi silk',
  'chiffon',
  'cotton',
  'cotton blend',
  'cotton cambric',
  'cotton linen',
  'cotton silk',
  'crepe',
  'denim',
  'dupion silk',
  'elastane',
  'georgette',
  'jacquard',
  'jute',
  'jute cotton',
  'jute silk',
  'khadi cotton',
  'kora muslin',
  'lace',
  'leather',
  'linen',
  'mulmul',
  'modal',
  'net',
  'nylon',
  'organza',
  'paper silk',
  'pashmina',
  'poly chiffon',
  'poly crepe',
  'poly georgette',
  'poly silk',
  'polycotton',
  'polyester',
  'rayon',
  'rayon slub',
  'satin',
  'shantoon',
  'silk',
  'silk blend',
  'soft silk',
  'super net',
  'synthetic',
  'taffeta silk',
  'tissue',
  'tussar silk',
  'velvet',
  'vichitra silk',
  'viscose',
  'viscose rayon',
  'voile',
  'wool',
]
export const NECK = [
  'alpha',
  'boat',
  'choker',
  'cowl',
  'halter',
  'hanley',
  'high',
  'keyhole',
  'mandarin',
  'notch',
  'off-shoulder',
  'one shoulder',
  'peter pan',
  'polo',
  'round',
  'scoop',
  'shawl collar',
  'shirt collar',
  'shoulder strap',
  'square',
  'strapless',
  'stylised',
  'surplice',
  'sweetheart',
  'tie-up',
  'turtle',
  'v-neck',
]
export const OCCASION = [
  'alpha',
  'casual',
  'ethnic casual',
  'ethnic party',
  'festive',
  'formal',
  'others',
  'party',
  'semiformal',
  'semicasual',
  'sports',
  'wedding',
]
export const STRAP_MATERIAL = [
  'alloy',
  'beads',
  'brass',
  'canvas',
  'ceramic',
  'fabric',
  'faux leather',
  'kundan',
  'leather',
  'metal',
  'pearl',
  'plastic',
  'PU',
  'resin',
  'rubber',
  'silicon',
  'stainless steel',
  'synthetic',
  'thread',
]
export const FRAME_MATERIAL = [
  'acetate',
  'acrylic',
  'alloy',
  'aluminium',
  'carbon fiber',
  'composite',
  'fiber',
  'fiber & plastic',
  'metal',
  'metal & plastic',
  'plastic',
  'polycarbonate',
  'rubber',
  'steel',
  'TR-90',
  'titanium',
]
export const BUCKLE_MATERIAL = ['alpha', 'metal', 'leather']
export const FORMULATION = [
  'cream',
  'foam',
  'gel',
  'lotion',
  'paste',
  'powder',
  'wax',
  'liquid',
  'bar',
  'butter',
  'spray',
  'mist',
  'roll_on',
  'serum',
  'solid',
  'mousse',
  'stick',
  'tablet',
  'capsule',
  'mask',
]
export const FRAME_SIZE = ['alpha', 'extra narrow', 'narrow', 'medium', 'wide', 'extra wide']
export const FEATURES = ['alpha', 'basic', 'pullover', 'threebuttoned', 'flared']
export const STONE_TYPE = ['alpha', 'precious', 'semi-precious', 'artificial']
export const PRINTER_OUTPUT = ['colour', 'monochrome']
export const SOCKS_LENGTH = ['ankle', 'knee', 'leg warmer', 'mid calf', 'no show', 'shoe liner', 'thigh high']
export const GENDER = ['male', 'female', 'boy', 'girl', 'infant', 'unisex']
export const PRESERVATIVE = [
  'benzoic acid',
  'carvacrol',
  'citric Aaid',
  'edta calcium disodium',
  'ethylene absorber',
  'hydro powder',
  'MSG',
  'oxygen absorber',
  'potassium benzoate',
  'propionic acid',
  'propylene glycol ppg',
  'sodium benzoate',
  'sodium bisulphite',
  'sodium lignosulfate',
  'sodium metabisulfite',
  'sodium propionate',
  'sodium citrate',
  'sorbic acid',
  'tripotassium phosphate',
  'trisodium citrate',
  'vacuum salt',
]
export const INSOLE = [
  'alpha',
  'arch support',
  'athletic',
  'comfort',
  'orthopedic',
  'rubber',
  'fur',
  'leather',
  'memory foam',
  'padded',
  'support',
]
export const HEMLINE = ['asymmetric', 'curved', 'high-low', 'straight', 'vented']
export const GRAIN_TYPE = ['broken', 'long', 'short', 'medium']
export const PLATING = ['alpha', 'brass', 'copper', 'gold', 'rose gold', 'rhodium', 'silver']
export const FLAVOUR = [
  'ajwain',
  'amla',
  'aniseed',
  'apple',
  'asafoetida',
  'assorted',
  'banana',
  'basil',
  'bay leaf',
  'blueberry',
  'butter',
  'caramel',
  'caraway',
  'cardamom',
  'chervil',
  'chillies',
  'chive',
  'chocolate',
  'cilantro',
  'cinnamon',
  'cloves',
  'cola',
  'coriander',
  'corn',
  'cranberry',
  'cumin',
  'curry leaves',
  'dill',
  'elaichi',
  'fennel',
  'fenugreek',
  'fruits',
  'galangal',
  'garlic',
  'ginger',
  'guava',
  'horseradish',
  'imli',
  'jeera',
  'kaffir lime leaf',
  'kasuri methi',
  'kokum',
  'lemon',
  'lemon grass',
  'mace',
  'mango',
  'marjoram',
  'methi',
  'mint',
  'mixed fruit',
  'mushroom',
  'mustard',
  'nutmeg',
  'onion',
  'orange',
  'oregano',
  'parsley',
  'peach',
  'pepper',
  'peppercorn',
  'peppermint',
  'pineapple',
  'pomegranate',
  'raspberry',
  'rosemary',
  'saffron',
  'sage',
  'spearmint',
  'star anise',
  'strawberry',
  'sweetmint',
  'tamarind',
  'tarragon',
  'thyme',
  'turmeric',
  'vanilla',
  'wasabi',
  'watermelon',
]
export const DIMENSION_UNIT = ['centimeter', 'meter']
export const BRISTLE_TYPE = ['natural', 'synthetic']
export const ORNAMENTATION = [
  'alpha',
  'aari work',
  'sequinned',
  'phulkari',
  'zari',
  'zardozi',
  'beads & stones',
  'threadwork',
  'chikankari',
  'gota patti',
  'mukaish',
  'patch',
  'kantha',
  'mirror',
]
export const WAIST_BAND = ['alpha', 'inner_elastic', 'outer_elastic']
export const FRAGRANCE = ['fresh', 'floral', 'earthy_woody', 'warm_spicy', 'fruity']
export const FRONT_STYLING = ['double-breasted', 'single-breasted', 'tuxedo']
export const POWER_TYPE = ['battery', 'solar']
export const SWEATSHIRT_TYPE = ['hooded', 'pullover']
export const CONNECTIVITY = ['bluetooth', 'LTE', 'wi-fi', 'wireless', 'USB', 'HDMI']
export const PADDING = ['alpha', 'lightly padded', 'heavily padded', 'non padded', 'removable padding']
export const FIT = ['alphanumeric', 'loose', 'regular', 'relax', 'skinny', 'slim', 'smart', 'ultra slim']
export const GEM_TYPE = [
  'alpha',
  'crystal',
  'pearl',
  'diamond',
  'american diamond',
  'aquamarine',
  'quartz',
  'zirconia',
  'garnet',
  'sapphire',
]
export const CONSCIOUS = ['cruelty_free', 'vegan', 'natural']
export const DISPLAY = ['alpha', 'analog', 'digital']
export const SEAM = ['alpha', 'cut_sew', 'seamless']
export const BASE_METAL = [
  'alpha',
  'gold',
  'silver',
  'brass',
  'alloy',
  'ceramic',
  'wood',
  'metal',
  'german silver',
  'leather',
  'plastic',
  'PU',
]
export const OUTSOLE = ['alpha', 'marking', 'non-marking']
export const BUCKLE_TYPE = ['alpha', 'cam', 'ratchet', 'roller', 'side release', 'slide', 'snap', 'tie']
export const BACKPACK_STYLE = [
  'buckle',
  'button',
  'drawstring',
  'flap',
  'hook & loop',
  'magnetic',
  'push lock',
  'snap',
  'twist lock',
  'zipper',
]
export const UOM = ['unit', 'dozen', 'gram', 'kilogram', 'tonne', 'litre', 'millilitre']
export const JEWELLERY_TYPE = [
  'statement',
  'stone',
  'pearl',
  'kundan',
  'oxidised',
  'tasse',
  'sterling_silver',
  'meenakari',
]
export const MIDSOLE = ['alpha', 'leather', 'PU', 'rubber']
export const COMPATIBLE_DEVICES = ['laptop', 'desktop', 'tablet', 'mobile phone']
export const SLEEVE_LENGTH = ['full', 'half', 'long', 'short', 'sleeveless', 'three-quarter']
export const BOTTOM_TYPE = ['capri', 'ethnic bottom', 'jeans', 'lounge pant', 'short', 'track pant', 'trouser']
export const MATERIAL_FINISH = ['alpha', 'embossed', 'embroidered']
export const FRAME_SHAPE = [
  'alpha',
  'aviator',
  'butterfly',
  'cat eye',
  'clubmaster',
  'contemporary',
  'geometric',
  'heart',
  'hexagon',
  'oval',
  'oversized',
  'rectangular',
  'round',
  'shield',
  'sports',
  'square',
  'teardrop',
  'wayfarer',
]

export const LOCK_TYPE = ['alpha', 'TSA', 'combination', 'numeric']
export const STRAP = [
  'alpha',
  'belt',
  'bracelet',
  'chain',
  'cross_body',
  'ergonomic',
  'halter',
  'one shoulder',
  'magnetic',
  'multiway',
  'regular',
  'sternum',
  'strapless',
  'yoke_style',
]
export const WASH_TYPE = ['clean', 'heavy', 'light']
export const SOLE_MATERIAL = [
  'croslite',
  'eva',
  'leather',
  'neolite',
  'phylon',
  'polyurethane',
  'PU',
  'PVC',
  'resin',
  'rubber',
  'synthetic',
  'TPR',
  'TPU',
  'tunit',
]
export const HAIR_TYPE = ['dry', 'normal', 'curly', 'straight', 'dull', 'oily', 'fine', 'thick', 'thin', 'wavy']
export const SEAM_TYPE = ['alpha', 'cut_sew', 'seamless']
export const PATTERN = [
  'alpha',
  'abstract',
  'animal',
  'bandhni',
  'camouflage',
  'checked',
  'chevron',
  'colourblocked',
  'dyed',
  'embellished',
  'embroidered',
  'ethnic motif',
  'faded',
  'floral',
  'geometric',
  'graphic print',
  'ikat',
  'lehriya',
  'mesh',
  'microprint',
  'ombre',
  'painted',
  'paisley',
  'perforations',
  'polka dots',
  'printed',
  'quirky',
  'solid',
  'striped',
  'temple',
  'textured',
  'tie-dyed',
  'tribal',
  'typography',
  'woven',
]
export const INGREDIENT = [
  'almond',
  'aloe_vera',
  'argan_oil',
  'avocado',
  'beeswax',
  'beetroot',
  'castor_oil',
  'chamomile',
  'charcoal',
  'clay',
  'coconut',
  'eucalyptus',
  'green_tea',
  'honey',
  'jojoba_oil',
  'lemon_grass',
  'moringa',
  'neem',
  'niacinamide',
  'papaya',
  'pomegranate',
  'rose',
  'salicylic_acid',
  'sandalwood',
  'shea_butter',
  'squalene',
  'sunflower',
  'tea_tree',
  'tulsi',
  'turmeric',
  'vitamin_A',
  'vitamin_C',
  'vitamin_E',
]
export const STORAGE_TYPE = ['SSD', 'HDD']
export const COLLAR = [
  'alpha',
  'button down',
  'mandarin',
  'club',
  'spread',
  'slim',
  'peter pan',
  'hood',
  'cutaway',
  'cuban',
  'wingtip',
  'built-up',
]
export const COVERAGE = ['alpha', 'full', 'half', 'medium', 'low', 'sheer']
export const SKIN_TYPE = ['dry', 'oily', 'sensitive', 'normal', 'all', 'very_dry']
export const SPECIAL_FEATURE = ['laser', 'GPS', 'night vision', 'frequency', 'AMOLED screen', 'Dolby audio']
export const FABRIC_FINISH = [
  'alpha',
  'satin',
  'crepe',
  'merserised',
  'printed',
  'painted',
  'embroidered',
  'patchwork',
  'woven',
  'knitted',
]
export const DIAL_SHAPE = [
  'alpha',
  'asymmetric',
  'diamond',
  'oval',
  'rectangle',
  'round',
  'square',
  'triangle',
  'thread',
]
export const BRUSH_TYPE = [
  'foundation',
  'stippling',
  'concealer',
  'powder',
  'blush',
  'contour',
  'bronzer',
  'highlight',
  'eyeshadow',
  'eyeshadow-crease',
  'eyeshadow-blending',
  'eye-liner',
  'mascara',
  'lip',
]
export const FACE_SHAPE = ['alpha', 'rectangular', 'oval', 'circular', 'square', 'triangular']
export const TOP_TYPE = ['jacket', 'shirt', 'sweater', 'sweatshirt', 't-shirt']
export const FRAME_STYLE = ['classic', 'trendy', 'designer', 'nerdy', 'retro', 'sporty']
export const BENEFIT = [
  'age_defying',
  'curling',
  'HD_photogenic',
  'lengthening',
  'luminous',
  'pore_minimising',
  'thickening',
  'volumizing',
  'waterproof',
  'long_lasting',
  'plumping',
  'transfer_proof',
  'transfer_resistant',
  'growth_boosting',
  'cuticle_care',
  'hydrating',
  'strengthening',
  'repairing',
]
export const UNIT = ['MB', 'GB', 'TB']
export const TOE_SHAPE = ['alpha', 'pointed', 'round', 'square']
export const FINISH = [
  'clear',
  'creme',
  'duochrome',
  'gel',
  'glitter',
  'glossy',
  'luminous',
  'matte',
  'metallic',
  'natural',
  'radiant',
  'shimmer',
  'satin',
  'special_effects',
  'tinted',
]
export const WAIST_RISE = ['alpha', 'low', 'high', 'med']
export const TYPE = ['Air Conditioner', 'Refrigerator', 'Vaccum Cleaner', 'Washing Machine']
export const MATERIAL = [
  'alpha',
  'acetate',
  'acrylic',
  'acrylonitrile',
  'aluminium',
  'battery',
  'brass',
  'canvas',
  'carbon',
  'cellulose',
  'cork',
  'cotton',
  'elastane',
  'elastodiene',
  'elastolefin',
  'ethylene',
  'EVA',
  'expanded',
  'faux leather',
  'foamed',
  'glass',
  'grey',
  'iron',
  'jute',
  'leather',
  'linen',
  'lycra',
  'lyocell',
  'mesh',
  'modal',
  'nubuck',
  'nylon',
  'polyamide',
  'polycarbonate',
  'polyester',
  'polyethylene',
  'polymethylpentene',
  'polyoxymethylene',
  'polypropylene',
  'polyurethane',
  'polyvinyl',
  'PU',
  'PVC',
  'rayon',
  'rice',
  'rubber',
  'sand',
  'silicon',
  'silk',
  'stainless',
  'steel',
  'styrene',
  'suede',
  'synthetic',
  'textile',
  'thermo',
  'thermoplastic',
  'tritan',
  'velvet',
  'viscose',
  'water',
  'wood',
  'wool',
  'zinc',
]
export const CLOSURE_TYPE = [
  'alpha',
  'back',
  'button',
  'front',
  'full-zip',
  'half-zip',
  'no-closure',
  'quarter-zip',
  'side',
  'slip-on',
  'tie-up',
]
export const TREND = [
  'alpha',
  'abstract',
  'geometric',
  'nautica',
  'animal',
  'indigo',
  'colour_block',
  'monochrome',
  'typography',
  'tribal',
  'floral',
]
export const SKIN_TONE = ['medium_wheatish', 'fair_light', 'dusky_dark']
export const PREFERENCE = [
  'acetone_free',
  'alcohol_free',
  'allergy_free',
  'ammonia_free',
  'animal_hair',
  'anti_inflammatory',
  'anti_oxidants',
  'clinically_proven',
  'collagen',
  'cruelty_free',
  'dermatologically_tested',
  'formaldehyde_free',
  'fragrance_free',
  'gluten_free',
  'halal_certified',
  'herbal',
  'hyaluronic_acid',
  'hypoallergenic',
  'mineral_oil_free',
  'natural',
  'niacinamide',
  'non_comedogenic',
  'non_vegetarian',
  'nut_free',
  'oil_free',
  'ophthalmologically_tested',
  'organic',
  'paba_free',
  'paraben_free',
  'paraffin_free',
  'petrochemical_free',
  'propleyne_free',
  'pthalate_free',
  'salicylic_acid',
  'silicone_free',
  'sls_free',
  'soap_free',
  'squalane',
  'sulphate_free',
  'sun_protection',
  'synthetic',
  'synthetic_color_free',
  'vegan',
  'vegetarian',
  'vitamin_A',
  'vitamin_C',
  'vitamin_E',
  'water_resistant',
  'waterproof',
  'waterless',
]
export const CONCERN = [
  'acne_blemish',
  'anti_ageing',
  'anti_pollution',
  'bad_breath',
  'blackhead_whitehead',
  'brightening',
  'cavity',
  'chapped_lip',
  'cleansing',
  'colour_protection',
  'cuticle_care',
  'dandruff',
  'dark_spot_pigmentation',
  'dry_frizzy_hair',
  'dryness',
  'dullness',
  'fine_lines_wrinkle',
  'firming',
  'hairfall_thinning',
  'heat_protection',
  'hydration',
  'menstrual_cycle',
  'odour',
  'oil_control',
  'plaque',
  'pores',
  'product_build_up',
  'soap_free',
  'split_end',
  'stretch_mark',
  'sun_protection',
  'tan_removal',
  'tangled_hair',
  'under_eye',
  'uneven_skin_tone',
  'waterproof',
]

const fashion_enum = {
  FOOTWEAR_TYPE,
  LENS_MATERIAL,
  FRAME_TYPE,
  SEASON,
  SPORT_TYPE,
  FASTEN_TYPE,
  FABRIC,
  NECK,
  OCCASION,
  STRAP_MATERIAL,
  FRAME_MATERIAL,
  BUCKLE_MATERIAL,
  FORMULATION,
  FRAME_SIZE,
  FEATURES,
  STONE_TYPE,
  PRINTER_OUTPUT,
  SOCKS_LENGTH,
  GENDER,
  PRESERVATIVE,
  INSOLE,
  HEMLINE,
  GRAIN_TYPE,
  PLATING,
  FLAVOUR,
  DIMENSION_UNIT,
  BRISTLE_TYPE,
  ORNAMENTATION,
  WAIST_BAND,
  FRAGRANCE,
  FRONT_STYLING,
  POWER_TYPE,
  SWEATSHIRT_TYPE,
  CONNECTIVITY,
  PADDING,
  FIT,
  GEM_TYPE,
  CONSCIOUS,
  DISPLAY,
  SEAM,
  BASE_METAL,
  OUTSOLE,
  BUCKLE_TYPE,
  BACKPACK_STYLE,
  UOM,
  JEWELLERY_TYPE,
  MIDSOLE,
  COMPATIBLE_DEVICES,
  SLEEVE_LENGTH,
  BOTTOM_TYPE,
  MATERIAL_FINISH,
  FRAME_SHAPE,
  LOCK_TYPE,
  STRAP,
  WASH_TYPE,
  SOLE_MATERIAL,
  HAIR_TYPE,
  SEAM_TYPE,
  PATTERN,
  INGREDIENT,
  STORAGE_TYPE,
  COLLAR,
  COVERAGE,
  SKIN_TYPE,
  SPECIAL_FEATURE,
  FABRIC_FINISH,
  DIAL_SHAPE,
  BRUSH_TYPE,
  FACE_SHAPE,
  TOP_TYPE,
  FRAME_STYLE,
  BENEFIT,
  UNIT,
  TOE_SHAPE,
  FINISH,
  WAIST_RISE,
  TYPE,
  MATERIAL,
  CLOSURE_TYPE,
  TREND,
  SKIN_TONE,
  PREFERENCE,
  CONCERN,
  // ... add the rest of the constants
}

// Export the Enums object
export default fashion_enum
