export const SIZE = [
  'XXS',
  'XS',
  'S',
  'M',
  'L',
  'XL',
  'XXL',
  'XXXL',
  '4XL',
  '5XL',
  '6XL',
  '7XL',
  '8XL',
  '9XL',
  '10XL',
  'Free Size',
]
export const FOOTWEAR_TYPE = [
  'boat shoes',
  'brogues',
  'clogs',
  'comfort sandals',
  'derbys',
  'driving shoes',
  'espadrilles',
  'flat boots',
  'flatforms',
  'gladiators',
  'kolhapuri',
  'loafers',
  'mojaris',
  'monks',
  'oxfords',
  'skate shoes',
  'sliders',
  'slip-on sneakers',
  'sneakers',
  'thong flip-flops',
  'trekking shoes',
]
export const LENS_MATERIAL = ['alpha', 'composite', 'glass', 'plastic', 'polycarbonate', 'trivex', 'high index']
export const FRAME_TYPE = ['alpha', 'full rim', 'half rim', 'rimless']
export const SEASON = ['alpha', 'rainy', 'winter', 'summer', 'autumn', 'fall_winter']
export const SPORT_TYPE = [
  'alpha',
  'running',
  'walking',
  'basketball',
  'baseball',
  'football',
  'soccer',
  'hockey',
  'lacrosse',
  'rugby',
  'volleyball',
  'training',
  'golf',
  'tennis',
  'cycling',
  'skateboarding',
]
export const FASTEN_TYPE = [
  'alpha',
  'ankle loop',
  'backstrap',
  'buckle',
  'closed back',
  'lace-up',
  'no back strap',
  'open back',
  'slip-on',
  'velcro',
  'zip',
]
export const FABRIC = [
  'alpha',
  'acrylic',
  'art silk',
  'bamboo',
  'chambray',
  'chanderi cotton',
  'chanderi silk',
  'chiffon',
  'cotton',
  'cotton blend',
  'cotton cambric',
  'cotton linen',
  'cotton silk',
  'crepe',
  'denim',
  'dupion silk',
  'elastane',
  'georgette',
  'jacquard',
  'jute',
  'jute cotton',
  'jute silk',
  'khadi cotton',
  'kora muslin',
  'lace',
  'leather',
  'linen',
  'mulmul',
  'modal',
  'net',
  'nylon',
  'organza',
  'paper silk',
  'pashmina',
  'poly chiffon',
  'poly crepe',
  'poly georgette',
  'poly silk',
  'polycotton',
  'polyester',
  'rayon',
  'rayon slub',
  'satin',
  'shantoon',
  'silk',
  'silk blend',
  'soft silk',
  'super net',
  'synthetic',
  'taffeta silk',
  'tissue',
  'tussar silk',
  'velvet',
  'vichitra silk',
  'viscose',
  'viscose rayon',
  'voile',
  'wool',
]
export const NECK = [
  'alpha',
  'boat',
  'choker',
  'cowl',
  'halter',
  'hanley',
  'high',
  'keyhole',
  'mandarin',
  'notch',
  'off-shoulder',
  'one shoulder',
  'peter pan',
  'polo',
  'round',
  'scoop',
  'shawl collar',
  'shirt collar',
  'shoulder strap',
  'square',
  'strapless',
  'stylised',
  'surplice',
  'sweetheart',
  'tie-up',
  'turtle',
  'v-neck',
]
export const OCCASION = [
  'alpha',
  'casual',
  'ethnic casual',
  'ethnic party',
  'festive',
  'formal',
  'others',
  'party',
  'semiformal',
  'semicasual',
  'sports',
  'wedding',
]
export const STRAP_MATERIAL = [
  'alloy',
  'beads',
  'brass',
  'canvas',
  'ceramic',
  'fabric',
  'faux leather',
  'kundan',
  'leather',
  'metal',
  'pearl',
  'plastic',
  'PU',
  'resin',
  'rubber',
  'silicon',
  'stainless steel',
  'synthetic',
  'thread',
]
export const FRAME_MATERIAL = [
  'acetate',
  'acrylic',
  'alloy',
  'aluminium',
  'carbon fiber',
  'composite',
  'fiber',
  'fiber & plastic',
  'metal',
  'metal & plastic',
  'plastic',
  'polycarbonate',
  'rubber',
  'steel',
  'TR-90',
  'titanium',
]
export const BUCKLE_MATERIAL = ['alpha', 'metal', 'leather']
export const FORMULATION = [
  'cream',
  'foam',
  'gel',
  'lotion',
  'paste',
  'powder',
  'wax',
  'liquid',
  'bar',
  'butter',
  'spray',
  'mist',
  'roll_on',
  'serum',
  'solid',
  'mousse',
  'stick',
  'tablet',
  'capsule',
  'mask',
]
export const FRAME_SIZE = ['alpha', 'extra narrow', 'narrow', 'medium', 'wide', 'extra wide']
export const FEATURES = ['alpha', 'basic', 'pullover', 'threebuttoned', 'flared']
export const STONE_TYPE = ['alpha', 'precious', 'semi-precious', 'artificial']
export const PRINTER_OUTPUT = ['colour', 'monochrome']
export const SOCKS_LENGTH = ['ankle', 'knee', 'leg warmer', 'mid calf', 'no show', 'shoe liner', 'thigh high']
export const GENDER = ['male', 'female', 'boy', 'girl', 'infant', 'unisex']
export const PRESERVATIVE = [
  'benzoic acid',
  'carvacrol',
  'citric Aaid',
  'edta calcium disodium',
  'ethylene absorber',
  'hydro powder',
  'MSG',
  'oxygen absorber',
  'potassium benzoate',
  'propionic acid',
  'propylene glycol ppg',
  'sodium benzoate',
  'sodium bisulphite',
  'sodium lignosulfate',
  'sodium metabisulfite',
  'sodium propionate',
  'sodium citrate',
  'sorbic acid',
  'tripotassium phosphate',
  'trisodium citrate',
  'vacuum salt',
]
export const INSOLE = [
  'alpha',
  'arch support',
  'athletic',
  'comfort',
  'orthopedic',
  'rubber',
  'fur',
  'leather',
  'memory foam',
  'padded',
  'support',
]
export const HEMLINE = ['asymmetric', 'curved', 'high-low', 'straight', 'vented']
export const GRAIN_TYPE = ['broken', 'long', 'short', 'medium']
export const PLATING = ['alpha', 'brass', 'copper', 'gold', 'rose gold', 'rhodium', 'silver']
export const FLAVOUR = [
  'ajwain',
  'amla',
  'aniseed',
  'apple',
  'asafoetida',
  'assorted',
  'banana',
  'basil',
  'bay leaf',
  'blueberry',
  'butter',
  'caramel',
  'caraway',
  'cardamom',
  'chervil',
  'chillies',
  'chive',
  'chocolate',
  'cilantro',
  'cinnamon',
  'cloves',
  'cola',
  'coriander',
  'corn',
  'cranberry',
  'cumin',
  'curry leaves',
  'dill',
  'elaichi',
  'fennel',
  'fenugreek',
  'fruits',
  'galangal',
  'garlic',
  'ginger',
  'guava',
  'horseradish',
  'imli',
  'jeera',
  'kaffir lime leaf',
  'kasuri methi',
  'kokum',
  'lemon',
  'lemon grass',
  'mace',
  'mango',
  'marjoram',
  'methi',
  'mint',
  'mixed fruit',
  'mushroom',
  'mustard',
  'nutmeg',
  'onion',
  'orange',
  'oregano',
  'parsley',
  'peach',
  'pepper',
  'peppercorn',
  'peppermint',
  'pineapple',
  'pomegranate',
  'raspberry',
  'rosemary',
  'saffron',
  'sage',
  'spearmint',
  'star anise',
  'strawberry',
  'sweetmint',
  'tamarind',
  'tarragon',
  'thyme',
  'turmeric',
  'vanilla',
  'wasabi',
  'watermelon',
]
export const DIMENSION_UNIT = ['centimeter', 'meter']
export const BRISTLE_TYPE = ['natural', 'synthetic']
export const ORNAMENTATION = [
  'alpha',
  'aari work',
  'sequinned',
  'phulkari',
  'zari',
  'zardozi',
  'beads & stones',
  'threadwork',
  'chikankari',
  'gota patti',
  'mukaish',
  'patch',
  'kantha',
  'mirror',
]
export const WAIST_BAND = ['alpha', 'inner_elastic', 'outer_elastic']
export const FRAGRANCE = ['fresh', 'floral', 'earthy_woody', 'warm_spicy', 'fruity']
export const FRONT_STYLING = ['double-breasted', 'single-breasted', 'tuxedo']
export const POWER_TYPE = ['battery', 'solar']
export const SWEATSHIRT_TYPE = ['hooded', 'pullover']
export const CONNECTIVITY = ['bluetooth', 'LTE', 'wi-fi', 'wireless', 'USB', 'HDMI']
export const PADDING = ['alpha', 'lightly padded', 'heavily padded', 'non padded', 'removable padding']
export const FIT = ['alphanumeric', 'loose', 'regular', 'relax', 'skinny', 'slim', 'smart', 'ultra slim']
export const GEM_TYPE = [
  'alpha',
  'crystal',
  'pearl',
  'diamond',
  'american diamond',
  'aquamarine',
  'quartz',
  'zirconia',
  'garnet',
  'sapphire',
]
export const CONSCIOUS = ['cruelty_free', 'vegan', 'natural']
export const DISPLAY = ['alpha', 'analog', 'digital']
export const SEAM = ['alpha', 'cut_sew', 'seamless']
export const BASE_METAL = [
  'alpha',
  'gold',
  'silver',
  'brass',
  'alloy',
  'ceramic',
  'wood',
  'metal',
  'german silver',
  'leather',
  'plastic',
  'PU',
]
export const OUTSOLE = ['alpha', 'marking', 'non-marking']
export const BUCKLE_TYPE = ['alpha', 'cam', 'ratchet', 'roller', 'side release', 'slide', 'snap', 'tie']
export const BACKPACK_STYLE = [
  'buckle',
  'button',
  'drawstring',
  'flap',
  'hook & loop',
  'magnetic',
  'push lock',
  'snap',
  'twist lock',
  'zipper',
]
export const UOM = ['unit', 'dozen', 'gram', 'kilogram', 'tonne', 'litre', 'millilitre']
export const JEWELLERY_TYPE = [
  'statement',
  'stone',
  'pearl',
  'kundan',
  'oxidised',
  'tasse',
  'sterling_silver',
  'meenakari',
]
export const MIDSOLE = ['alpha', 'leather', 'PU', 'rubber']
export const COMPATIBLE_DEVICES = ['laptop', 'desktop', 'tablet', 'mobile phone']
export const SLEEVE_LENGTH = ['full', 'half', 'long', 'short', 'sleeveless', 'three-quarter']
export const BOTTOM_TYPE = ['capri', 'ethnic bottom', 'jeans', 'lounge pant', 'short', 'track pant', 'trouser']
export const MATERIAL_FINISH = ['alpha', 'embossed', 'embroidered']
export const FRAME_SHAPE = [
  'alpha',
  'aviator',
  'butterfly',
  'cat eye',
  'clubmaster',
  'contemporary',
  'geometric',
  'heart',
  'hexagon',
  'oval',
  'oversized',
  'rectangular',
  'round',
  'shield',
  'sports',
  'square',
  'teardrop',
  'wayfarer',
]
export const COLOUR = [
  'abbey',
  'acadia',
  'acapulco',
  'aero blue',
  'affair',
  'akaroa',
  'alabaster',
  'albescent white',
  'algae green',
  'alice blue',
  'alizarin crimson',
  'allports',
  'almond',
  'almond frost',
  'alpine',
  'alto',
  'aluminium',
  'amaranth',
  'amazon',
  'amber',
  'americano',
  'amethyst',
  'amethyst smoke',
  'amour',
  'amulet',
  'anakiwa',
  'antique brass',
  'antique bronze',
  'anzac',
  'apache',
  'apple',
  'apple blossom',
  'apple green',
  'apricot',
  'apricot peach',
  'apricot white',
  'aqua deep',
  'aqua forest',
  'aqua haze',
  'aqua island',
  'aqua spring',
  'aqua squeeze',
  'aquamarine',
  'aquamarine blue',
  'arapawa',
  'armadillo',
  'arrowtown',
  'ash',
  'asparagus',
  'asphalt',
  'astra',
  'astral',
  'astronaut',
  'astronaut blue',
  'athens gray',
  'aths special',
  'atlantis',
  'atoll',
  'atomic tangerine',
  'au chico',
  'aubergine',
  'australian mint',
  'avocado',
  'axolotl',
  'azalea',
  'aztec',
  'azure',
  'azure radiance',
  'baby blue',
  'bahama blue',
  'bahia',
  'baja white',
  'bali hai',
  'baltic sea',
  'bamboo',
  'banana mania',
  'bandicoot',
  'barberry',
  'barley corn',
  'barley white',
  'barossa',
  'bastille',
  'battleship gray',
  'bay leaf',
  'bay of many',
  'bazaar',
  'bean  ',
  'beauty bush',
  'beaver',
  'beeswax',
  'beige',
  'bermuda',
  'bermuda gray',
  'beryl green',
  'bianca',
  'big stone',
  'bilbao',
  'biloba flower',
  'birch',
  'bird flower',
  'biscay',
  'bismark',
  'bison hide',
  'bistre',
  'bitter',
  'bitter lemon',
  'bittersweet',
  'bizarre',
  'black',
  'black bean',
  'black forest',
  'black haze',
  'black marlin',
  'black olive',
  'black pearl',
  'black rock',
  'black rose',
  'black russian',
  'black squeeze',
  'black white',
  'blackberry',
  'blackcurrant',
  'blaze orange',
  'bleach white',
  'bleached cedar',
  'blizzard blue',
  'blossom',
  'blue',
  'blue bayoux',
  'blue bell',
  'blue chalk',
  'blue charcoal',
  'blue chill',
  'blue diamond',
  'blue dianne',
  'blue gem',
  'blue haze',
  'blue lagoon',
  'blue marguerite',
  'blue ribbon',
  'blue romance',
  'blue smoke',
  'blue stone',
  'blue violet',
  'blue whale',
  'blue zodiac',
  'blumine',
  'blush',
  'blush pink',
  'bombay',
  'bon jour',
  'bondi blue',
  'bone',
  'bordeaux',
  'bossanova',
  'boston blue',
  'botticelli',
  'bottle green',
  'boulder',
  'bouquet',
  'bourbon',
  'bracken',
  'brandy',
  'brandy punch',
  'brandy rose',
  'breaker bay',
  'brick red',
  'bridal heath',
  'bridesmaid',
  'bright gray',
  'bright green',
  'bright red',
  'bright sun',
  'bright turquoise',
  'brilliant rose',
  'brink pink',
  'bronco',
  'bronze',
  'bronze olive',
  'bronzetone',
  'broom',
  'brown',
  'brown bramble',
  'brown derby',
  'brown pod',
  'brown rust',
  'brown tumbleweed',
  'bubbles',
  'buccaneer',
  'bud',
  'buddha gold',
  'buff',
  'bulgarian rose',
  'bull shot',
  'bunker',
  'bunting',
  'burgundy',
  'burnham',
  'burning orange',
  'burning sand',
  'burnt maroon',
  'burnt orange',
  'burnt sienna',
  'burnt umber',
  'bush',
  'buttercup',
  'buttered rum',
  'butterfly bush',
  'buttermilk',
  'buttery white',
  'cab sav',
  'cabaret',
  'cabbage pont',
  'cactus',
  'cadet blue',
  'cadillac',
  'cafe royale',
  'calico',
  'california',
  'calypso',
  'camarone',
  'camelot',
  'cameo',
  'camouflage',
  'camouflage green',
  'can can',
  'canary',
  'candlelight',
  'candy corn',
  'cannon black',
  'cannon pink',
  'cape cod',
  'cape honey',
  'cape palliser',
  'caper',
  'caramel',
  'cararra',
  'cardin green',
  'cardinal',
  'cardinal pink',
  'careys pink',
  'caribbean green',
  'carissma',
  'carla',
  'carmine',
  'carnaby tan',
  'carnation',
  'carnation pink',
  'carousel pink',
  'carrot orange',
  'casablanca',
  'casal',
  'cascade',
  'cashmere',
  'casper',
  'castro',
  'catalina blue',
  'catskill white',
  'cavern pink',
  'cedar',
  'cedar wood finish',
  'celadon',
  'celery',
  'celeste',
  'cello',
  'celtic',
  'cement',
  'ceramic',
  'cerise',
  'cerise red',
  'cerulean',
  'cerulean blue',
  'chablis',
  'chalet green',
  'chalky',
  'chambray',
  'chamois',
  'champagne',
  'chantilly',
  'charade',
  'chardon',
  'chardonnay',
  'charlotte',
  'charm',
  'chartreuse',
  'chartreuse yellow',
  'chateau green',
  'chatelle',
  'chathams blue',
  'chelsea cucumber',
  'chelsea gem',
  'chenin',
  'cherokee',
  'cherry pie',
  'cherrywood',
  'cherub',
  'chestnut',
  'chestnut rose',
  'chetwode blue',
  'chicago',
  'chiffon',
  'chilean fire',
  'chilean heath',
  'china ivory',
  'chino',
  'chinook',
  'chocolate',
  'christalle',
  'christi',
  'christine',
  'chrome white',
  'cinder',
  'cinderella',
  'cinnabar',
  'cinnamon',
  'cioccolato',
  'citrine white',
  'citron',
  'citrus',
  'clairvoyant',
  'clam shell',
  'claret',
  'classic rose',
  'clay ash',
  'clay creek',
  'clear day',
  'clementine',
  'clinker',
  'cloud',
  'cloud burst',
  'cloudy',
  'clover',
  'cobalt',
  'cocoa bean',
  'cocoa brown',
  'coconut cream',
  'cod gray',
  'coffee',
  'coffee bean',
  'cognac',
  'cola',
  'cold purple',
  'cold turkey',
  'colonial white',
  'comet',
  'como',
  'conch',
  'concord',
  'concrete',
  'confetti',
  'congo brown',
  'congress blue',
  'conifer',
  'contessa',
  'copper',
  'copper canyon',
  'copper rose',
  'copper rust',
  'copperfield',
  'coral',
  'coral red',
  'coral reef',
  'coral tree',
  'corduroy',
  'coriander',
  'cork',
  'corn',
  'corn field',
  'corn harvest',
  'cornflower',
  'cornflower blue',
  'cornflower lilac',
  'corvette',
  'cosmic',
  'cosmos',
  'costa del sol',
  'cotton candy',
  'cotton seed',
  'county green',
  'cowboy',
  'crail',
  'cranberry',
  'crater brown',
  'cream',
  'cream brulee',
  'cream can',
  'creole',
  'crete',
  'crimson',
  'crocodile',
  'crown of thorns',
  'crowshead',
  'cruise',
  'crusoe',
  'crusta',
  'cumin',
  'cumulus',
  'cupid',
  'curious blue',
  'cutty sark',
  'cyan / aqua',
  'cyprus',
  'daintree',
  'dairy cream',
  'daisy bush',
  'dallas',
  'dandelion',
  'danube',
  'dark blue',
  'dark burgundy',
  'dark ebony',
  'dark fern',
  'dark tan',
  'dawn',
  'dawn pink',
  'de york',
  'deco',
  'deep blue',
  'deep blush',
  'deep bronze',
  'deep cerulean',
  'deep cove',
  'deep fir',
  'deep forest green',
  'deep koamaru',
  'deep oak',
  'deep sapphire',
  'deep sea',
  'deep sea green',
  'deep teal',
  'del rio',
  'dell',
  'delta',
  'deluge',
  'denim',
  'derby',
  'desert',
  'desert sand',
  'desert storm',
  'dew',
  'di serria',
  'diesel',
  'dingley',
  'disco',
  'dixie',
  'dodger blue',
  'dolly',
  'dolphin',
  'domino',
  'don juan',
  'donkey brown',
  'dorado',
  'double colonial white',
  'double pearl lusta',
  'double spanish white',
  'dove gray',
  'downriver',
  'downy',
  'driftwood',
  'drover',
  'dull lavender',
  'dune',
  'dust storm',
  'dusty gray',
  'eagle',
  'earls green',
  'early dawn',
  'east bay',
  'east side',
  'eastern blue',
  'ebb',
  'ebony',
  'ebony clay',
  'eclipse',
  'ecru white',
  'ecstasy',
  'eden',
  'edgewater',
  'edward',
  'egg sour',
  'egg white',
  'eggplant',
  'el paso',
  'el salva',
  'electric lime',
  'electric violet',
  'elephant',
  'elf green',
  'elm',
  'emerald',
  'eminence',
  'emperor',
  'empress',
  'endeavour',
  'energy yellow',
  'english holly',
  'english walnut',
  'envy',
  'equator',
  'espresso',
  'eternity',
  'eucalyptus',
  'eunry',
  'evening sea',
  'everglade',
  'faded jade',
  'fair pink',
  'falcon',
  'fall green',
  'falu red',
  'fantasy',
  'fedora',
  'feijoa',
  'fern',
  'fern frond',
  'fern green',
  'ferra',
  'festival',
  'feta',
  'fiery orange',
  'finch',
  'finlandia',
  'finn',
  'fiord',
  'fire',
  'fire bush',
  'firefly',
  'flame pea',
  'flamenco',
  'flamingo',
  'flax',
  'flax smoke',
  'flesh',
  'flint',
  'flirt',
  'flush mahogany',
  'flush orange',
  'foam',
  'fog',
  'foggy gray',
  'forest green',
  'forget me not',
  'fountain blue',
  'frangipani',
  'french gray',
  'french lilac',
  'french pass',
  'french rose',
  'fresh eggplant',
  'friar gray',
  'fringy flower',
  'froly',
  'frost',
  'frosted mint',
  'frostee',
  'fruit salad',
  'fuchsia blue',
  'fuchsia pink',
  'fuego',
  'fuel yellow',
  'fun blue',
  'fun green',
  'fuscous gray',
  'fuzzy wuzzy brown',
  'gable green',
  'gallery',
  'galliano',
  'gamboge',
  'geebung',
  'genoa',
  'geraldine',
  'geyser',
  'ghost',
  'gigas',
  'gimblet',
  'gin',
  'gin fizz',
  'givry',
  'glacier',
  'glade green',
  'go ben',
  'goblin',
  'gold',
  'gold drop',
  'gold sand',
  'gold tips',
  'golden bell',
  'golden dream',
  'golden fizz',
  'golden glow',
  'golden grass',
  'golden sand',
  'golden tainoi',
  'goldenrod',
  'gondola',
  'gordons green',
  'gorse',
  'gossamer',
  'gossip',
  'gothic',
  'governor bay',
  'grain brown',
  'grandis',
  'granite green',
  'granny apple',
  'granny smith',
  'granny smith apple',
  'grape',
  'graphite',
  'gravel',
  'gray',
  'gray asparagus',
  'gray chateau',
  'gray nickel',
  'gray nurse',
  'gray olive',
  'gray suit',
  'green',
  'green haze',
  'green house',
  'green kelp',
  'green leaf',
  'green mist',
  'green pea',
  'green smoke',
  'green spring',
  'green vogue',
  'green waterloo',
  'green white',
  'green yellow',
  'grenadier',
  'guardsman red',
  'gulf blue',
  'gulf stream',
  'gull gray',
  'gum leaf',
  'gumbo',
  'gun powder',
  'gunsmoke',
  'gurkha',
  'hacienda',
  'hairy heath',
  'haiti',
  'half and half',
  'half baked',
  'half colonial white',
  'half dutch white',
  'half spanish white',
  'hampton',
  'harlequin',
  'harp',
  'harvest gold',
  'havelock blue',
  'hawaiian tan',
  'hawkes blue',
  'heath',
  'heather',
  'heathered gray',
  'heavy metal',
  'heliotrope',
  'hemlock',
  'hemp',
  'hibiscus',
  'highland',
  'hillary',
  'himalaya',
  'hint of green',
  'hint of red',
  'hint of yellow',
  'hippie blue',
  'hippie green',
  'hippie pink',
  'hit gray',
  'hit pink',
  'hokey pokey',
  'hoki',
  'holly',
  'hollywood cerise',
  'honey flower',
  'honeysuckle',
  'hopbush',
  'horizon',
  'horses neck',
  'hot cinnamon',
  'hot pink',
  'hot toddy',
  'humming bird',
  'hunter green',
  'hurricane',
  'husk',
  'ice cold',
  'iceberg',
  'illusion',
  'inch worm',
  'indian khaki',
  'indian tan',
  'indigo',
  'indochine',
  'international klein blue',
  'international orange',
  'irish coffee',
  'iroko',
  'iron',
  'ironside gray',
  'ironstone',
  'island spice',
  'ivory',
  'jacaranda',
  'jacarta',
  'jacko bean',
  'jacksons purple',
  'jade',
  'jaffa',
  'jagged ice',
  'jagger',
  'jaguar',
  'jambalaya',
  'janna',
  'japanese laurel',
  'japanese maple',
  'japonica',
  'java',
  'jazzberry jam',
  'jelly bean',
  'jet stream',
  'jewel',
  'jon',
  'jonquil',
  'jordy blue',
  'judge gray',
  'jumbo',
  'jungle green',
  'jungle mist',
  'juniper',
  'just right',
  'kabul',
  'kaitoke green',
  'kangaroo',
  'karaka',
  'karry',
  'kashmir blue',
  'kelp',
  'kenyan copper',
  'keppel',
  'key lime pie',
  'khaki',
  'kidnapper',
  'kilamanjaro',
  'killarney',
  'kimberly',
  'kingfisher daisy',
  'kobi',
  'kokoda',
  'korma',
  'koromiko',
  'kournikova',
  'kumera',
  'la palma',
  'la rioja',
  'las palmas',
  'laser',
  'laser lemon',
  'laurel',
  'lavender',
  'lavender blush',
  'lavender gray',
  'lavender magenta',
  'lavender pink',
  'lavender purple',
  'lavender rose',
  'leather',
  'lemon',
  'lemon chiffon',
  'lemon ginger',
  'lemon grass',
  'light apricot',
  'light orchid',
  'light wisteria',
  'lightning yellow',
  'lilac',
  'lilac bush',
  'lily',
  'lily white',
  'lima',
  'lime',
  'limeade',
  'limed ash',
  'limed oak',
  'limed spruce',
  'linen',
  'link water',
  'lipstick',
  'lisbon brown',
  'livid brown',
  'loafer',
  'loblolly',
  'lochinvar',
  'lochmara',
  'locust',
  'log cabin',
  'logan',
  'lola',
  'london hue',
  'lonestar',
  'lotus',
  'loulou',
  'lucky',
  'lucky point',
  'lunar green',
  'luxor gold',
  'lynch',
  'mabel',
  'macaroni and cheese',
  'madang',
  'madison',
  'madras',
  'magenta / fuchsia',
  'magic mint',
  'magnolia',
  'mahogany',
  'mai tai',
  'maize',
  'makara',
  'mako',
  'malachite',
  'malibu',
  'mallard',
  'malta',
  'mamba',
  'manatee',
  'mandalay',
  'mandy',
  'mandys pink',
  'mango tango',
  'manhattan',
  'mantis',
  'mantle',
  'manz',
  'mardi gras',
  'marigold',
  'marigold yellow',
  'mariner',
  'maroon',
  'maroon flush',
  'maroon oak',
  'marshland',
  'martini',
  'martinique',
  'marzipan',
  'masala',
  'matisse',
  'matrix',
  'matterhorn',
  'mauve',
  'mauvelous',
  'maverick',
  'medium carmine',
  'medium purple',
  'medium red violet',
  'melanie',
  'melanzane',
  'melon',
  'melrose',
  'mercury',
  'merino',
  'merlin',
  'merlot',
  'metallic bronze',
  'metallic copper',
  'meteor',
  'meteorite',
  'mexican red',
  'mid gray',
  'midnight',
  'midnight blue',
  'midnight moss',
  'mikado',
  'milan',
  'milano red',
  'milk punch',
  'millbrook',
  'mimosa',
  'mindaro',
  'mine shaft',
  'mineral green',
  'ming',
  'minsk',
  'mint green',
  'mint julep',
  'mint tulip',
  'mirage',
  'mischka',
  'mist gray',
  'mobster',
  'moccaccino',
  'mocha',
  'mojo',
  'mona lisa',
  'monarch',
  'mondo',
  'mongoose',
  'monsoon',
  'monte carlo',
  'monza',
  'moody blue',
  'moon glow',
  'moon mist',
  'moon raker',
  'morning glory',
  'morocco brown',
  'mortar',
  'mosque',
  'moss green',
  'mountain meadow',
  'mountain mist',
  'mountbatten pink',
  'muddy waters',
  'muesli',
  'mulberry',
  'mulberry wood',
  'mule fawn',
  'mulled wine',
  'mustard',
  'my pink',
  'my sin',
  'mystic',
  'nandor',
  'napa',
  'narvik',
  'natural gray',
  'navajo white',
  'navy blue',
  'nebula',
  'negroni',
  'neon carrot',
  'nepal',
  'neptune',
  'nero',
  'nevada',
  'new orleans',
  'new york pink',
  'niagara',
  'night rider',
  'night shadz',
  'nile blue',
  'nobel',
  'nomad',
  'norway',
  'nugget',
  'nutmeg',
  'nutmeg wood finish',
  'oasis',
  'observatory',
  'ocean green',
  'ochre',
  'off green',
  'off yellow',
  'oil',
  'old brick',
  'old copper',
  'old gold',
  'old lace',
  'old lavender',
  'old rose',
  'olive',
  'olive drab',
  'olive green',
  'olive haze',
  'olivetone',
  'olivine',
  'onahau',
  'onion',
  'opal',
  'opium',
  'oracle',
  'orange',
  'orange peel',
  'orange roughy',
  'orange white',
  'orchid',
  'orchid white',
  'oregon',
  'orient',
  'oriental pink',
  'orinoco',
  'oslo gray',
  'ottoman',
  'outer space',
  'outrageous orange',
  'oxford blue',
  'oxley',
  'oyster bay',
  'oyster pink',
  'paarl',
  'pablo',
  'pacific blue',
  'pacifika',
  'paco',
  'padua',
  'pale canary',
  'pale leaf',
  'pale oyster',
  'pale prim',
  'pale rose',
  'pale sky',
  'pale slate',
  'palm green',
  'palm leaf',
  'pampas',
  'panache',
  'pancho',
  'papaya whip',
  'paprika',
  'paradiso',
  'parchment',
  'paris daisy',
  'paris m',
  'paris white',
  'parsley',
  'pastel green',
  'pastel pink',
  'patina',
  'pattens blue',
  'paua',
  'pavlova',
  'peach',
  'peach cream',
  'peach orange',
  'peach schnapps',
  'peach yellow',
  'peanut',
  'pear',
  'pearl bush',
  'pearl lusta',
  'peat',
  'pelorous',
  'peppermint',
  'perano',
  'perfume',
  'periglacial blue',
  'periwinkle',
  'periwinkle gray',
  'persian blue',
  'persian green',
  'persian indigo',
  'persian pink',
  'persian plum',
  'persian red',
  'persian rose',
  'persimmon',
  'peru tan',
  'pesto',
  'petite orchid',
  'pewter',
  'pharlap',
  'picasso',
  'pickled bean',
  'pickled bluewood',
  'picton blue',
  'pig pink',
  'pigeon post',
  'pigment indigo',
  'pine cone',
  'pine glade',
  'pine green',
  'pine tree',
  'pink',
  'pink flamingo',
  'pink flare',
  'pink lace',
  'pink lady',
  'pink salmon',
  'pink swan',
  'piper',
  'pipi',
  'pippin',
  'pirate gold',
  'pistachio',
  'pixie green',
  'pizazz',
  'pizza',
  'plantation',
  'plum',
  'pohutukawa',
  'polar',
  'polo blue',
  'pomegranate',
  'pompadour',
  'porcelain',
  'porsche',
  'port gore',
  'portafino',
  'portage',
  'portica',
  'pot pourri',
  'potters clay',
  'powder ash',
  'powder blue',
  'prairie sand',
  'prelude',
  'prim',
  'primrose',
  'provincial pink',
  'prussian blue',
  'puce',
  'pueblo',
  'puerto rico',
  'pumice',
  'pumpkin',
  'pumpkin skin',
  'punch',
  'punga',
  'purple',
  'purple heart',
  'purple mountain majesty',
  'purple pizzazz',
  'putty',
  'quarter pearl lusta',
  'quarter spanish white',
  'quicksand',
  'quill gray',
  'quincy',
  'racing green',
  'radical red',
  'raffia',
  'rainee',
  'rajah',
  'rangitoto',
  'rangoon green',
  'raven',
  'raw sienna',
  'raw umber',
  'razzle dazzle rose',
  'razzmatazz',
  'rebel',
  'red',
  'red beech',
  'red berry',
  'red damask',
  'red devil',
  'red orange',
  'red oxide',
  'red ribbon',
  'red robin',
  'red stage',
  'red violet',
  'redwood',
  'reef',
  'reef gold',
  'regal blue',
  'regent gray',
  'regent st blue',
  'remy',
  'reno sand',
  'resolution blue',
  'revolver',
  'rhino',
  'rice cake',
  'rice flower',
  'rich gold',
  'rio grande',
  'ripe lemon',
  'ripe plum',
  'riptide',
  'river bed',
  'rob roy',
  'robin egg blue',
  'rock',
  'rock blue',
  'rock spray',
  'rodeo dust',
  'rolling stone',
  'roman',
  'roman coffee',
  'romance',
  'romantic',
  'ronchi',
  'roof terracotta',
  'rope',
  'rose',
  'rose bud',
  'rose bud cherry',
  'rose fog',
  'rose of sharon',
  'rose white',
  'rosewood',
  'roti',
  'rouge',
  'royal blue',
  'royal heath',
  'royal purple',
  'rum',
  'rum swizzle',
  'russet',
  'russett',
  'rust',
  'rustic red',
  'rusty nail',
  'saddle',
  'saddle brown',
  'saffron',
  'saffron mango',
  'sage',
  'sahara',
  'sahara sand',
  'sail',
  'salem',
  'salmon',
  'salomie',
  'salt box',
  'saltpan',
  'sambuca',
  'san felix',
  'san juan',
  'san marino',
  'sand dune',
  'sandal',
  'sandrift',
  'sandstone',
  'sandwisp',
  'sandy beach',
  'sandy brown',
  'sangria',
  'sanguine brown',
  'santa fe',
  'santas gray',
  'sapling',
  'sapphire',
  'saratoga',
  'satin linen',
  'sauvignon',
  'sazerac',
  'scampi',
  'scandal',
  'scarlet',
  'scarlet gum',
  'scarlett',
  'scarpa flow',
  'schist',
  'school bus yellow',
  'schooner',
  'science blue',
  'scooter',
  'scorpion',
  'scotch mist',
  'screamin green',
  'sea buckthorn',
  'sea green',
  'sea mist',
  'sea nymph',
  'sea pink',
  'seagull',
  'seance',
  'seashell',
  'seashell peach',
  'seaweed',
  'selago',
  'selective yellow',
  'sepia',
  'sepia black',
  'sepia skin',
  'serenade',
  'shadow',
  'shadow green',
  'shady lady',
  'shakespeare',
  'shalimar',
  'shamrock',
  'shark',
  'sherpa blue',
  'sherwood green',
  'shilo',
  'shingle fawn',
  'ship cove',
  'ship gray',
  'shiraz',
  'shocking',
  'shocking pink',
  'shuttle gray',
  'siam',
  'sidecar',
  'silk',
  'silver',
  'silver chalice',
  'silver rust',
  'silver sand',
  'silver tree',
  'sinbad',
  'siren',
  'sirocco',
  'sisal',
  'skeptic',
  'sky blue',
  'slate gray',
  'smalt',
  'smalt blue',
  'smoky',
  'snow drift',
  'snow flurry',
  'snowy mint',
  'snuff',
  'soapstone',
  'soft amber',
  'soft peach',
  'solid pink',
  'solitaire',
  'solitude',
  'sorbus',
  'sorrell brown',
  'soya bean',
  'spanish green',
  'spectra',
  'spice',
  'spicy mix',
  'spicy mustard',
  'spicy pink',
  'spindle',
  'spray',
  'spring green',
  'spring leaves',
  'spring rain',
  'spring sun',
  'spring wood',
  'sprout',
  'spun pearl',
  'squirrel',
  'st tropaz',
  'stack',
  'star dust',
  'stark white',
  'starship',
  'steel blue',
  'steel gray',
  'stiletto',
  'stonewall',
  'storm dust',
  'storm gray',
  'stratos',
  'straw',
  'strikemaster',
  'stromboli',
  'studio',
  'submarine',
  'sugar cane',
  'sulu',
  'summer green',
  'sun',
  'sundance',
  'sundown',
  'sunflower',
  'sunglo',
  'sunglow',
  'sunset orange',
  'sunshade',
  'supernova',
  'surf',
  'surf crest',
  'surfie green',
  'sushi',
  'suva gray',
  'swamp',
  'swamp green',
  'swans down',
  'sweet corn',
  'sweet pink',
  'swirl',
  'swiss coffee',
  'sycamore',
  'tabasco',
  'tacao',
  'tacha',
  'tahiti gold',
  'tahuna sands',
  'tall poppy',
  'tallow',
  'tamarillo',
  'tamarind',
  'tan',
  'tan hide',
  'tana',
  'tangaroa',
  'tangerine',
  'tango',
  'tapa',
  'tapestry',
  'tara',
  'tarawera',
  'tasman',
  'taupe',
  'taupe gray',
  'tawny port',
  'te papa green',
  'tea',
  'tea green',
  'teak',
  'teal',
  'teal blue',
  'temptress',
  'tenn',
  'tequila',
  'terracotta',
  'texas',
  'texas rose',
  'thatch',
  'thatch green',
  'thistle',
  'thistle green',
  'thunder',
  'thunderbird',
  'tia maria',
  'tiara',
  'tiber',
  'tickle me pink',
  'tidal',
  'tide',
  'timber green',
  'timberwolf',
  'titan white',
  'toast',
  'tobacco brown',
  'toledo',
  'tolopea',
  'tom thumb',
  'tonys pink',
  'topaz',
  'torch red',
  'torea bay',
  'tory blue',
  'tosca',
  'totem pole',
  'tower gray',
  'tradewind',
  'tranquil',
  'travertine',
  'tree poppy',
  'treehouse',
  'trendy green',
  'trendy pink',
  'trinidad',
  'tropical blue',
  'tropical rain forest',
  'trout',
  'true v',
  'tuatara',
  'tuft bush',
  'tulip tree',
  'tumbleweed',
  'tuna',
  'tundora',
  'turbo',
  'turkish rose',
  'turmeric',
  'turquoise',
  'turquoise blue',
  'turtle green',
  'tuscany',
  'tusk',
  'tussock',
  'tutu',
  'twilight',
  'twilight blue',
  'twine',
  'tyrian purple',
  'ultramarine',
  'valencia',
  'valentino',
  'valhalla',
  'van cleef',
  'vanilla',
  'vanilla ice',
  'varden',
  'venetian red',
  'venice blue',
  'venus',
  'verdigris',
  'verdun green',
  'vermilion',
  'vesuvius',
  'victoria',
  'vida loca',
  'viking',
  'vin rouge',
  'viola',
  'violent violet',
  'violet',
  'violet eggplant',
  'violet red',
  'viridian',
  'viridian green',
  'vis vis',
  'vista blue',
  'vista white',
  'vivid tangerine',
  'vivid violet',
  'voodoo',
  'vulcan',
  'wafer',
  'waikawa gray',
  'waiouru',
  'walnut',
  'wasabi',
  'water leaf',
  'watercourse',
  'waterloo ',
  'wattle',
  'watusi',
  'wax flower',
  'we peep',
  'web orange',
  'wedgewood',
  'well read',
  'west coast',
  'west side',
  'westar',
  'wewak',
  'wheat',
  'wheatfield',
  'whiskey',
  'whisper',
  'white',
  'white ice',
  'white lilac',
  'white linen',
  'white pointer',
  'white rock',
  'wild blue yonder',
  'wild rice',
  'wild sand',
  'wild strawberry',
  'wild watermelon',
  'wild willow',
  'william',
  'willow brook',
  'willow grove',
  'windsor',
  'wine berry',
  'winter hazel',
  'wisp pink',
  'wisteria',
  'wistful',
  'witch haze',
  'wood bark',
  'woodland',
  'woodrush',
  'woodsmoke',
  'woody brown',
  'xanadu',
  'yellow',
  'yellow green',
  'yellow metal',
  'yellow orange',
  'yellow sea',
  'your pink',
  'yukon gold',
  'yuma',
  'zambezi',
  'zanah',
  'zest',
  'zeus',
  'ziggurat',
  'zinnwaldite',
  'zircon',
  'zombie',
  'zorba',
  'zuccini',
  'zumthor',
]

export const LOCK_TYPE = ['alpha', 'TSA', 'combination', 'numeric']
export const STRAP = [
  'alpha',
  'belt',
  'bracelet',
  'chain',
  'cross_body',
  'ergonomic',
  'halter',
  'one shoulder',
  'magnetic',
  'multiway',
  'regular',
  'sternum',
  'strapless',
  'yoke_style',
]
export const WASH_TYPE = ['clean', 'heavy', 'light']
export const SOLE_MATERIAL = [
  'croslite',
  'eva',
  'leather',
  'neolite',
  'phylon',
  'polyurethane',
  'PU',
  'PVC',
  'resin',
  'rubber',
  'synthetic',
  'TPR',
  'TPU',
  'tunit',
]
export const HAIR_TYPE = ['dry', 'normal', 'curly', 'straight', 'dull', 'oily', 'fine', 'thick', 'thin', 'wavy']
export const SEAM_TYPE = ['alpha', 'cut_sew', 'seamless']
export const PATTERN = [
  'alpha',
  'abstract',
  'animal',
  'bandhni',
  'camouflage',
  'checked',
  'chevron',
  'colourblocked',
  'dyed',
  'embellished',
  'embroidered',
  'ethnic motif',
  'faded',
  'floral',
  'geometric',
  'graphic print',
  'ikat',
  'lehriya',
  'mesh',
  'microprint',
  'ombre',
  'painted',
  'paisley',
  'perforations',
  'polka dots',
  'printed',
  'quirky',
  'solid',
  'striped',
  'temple',
  'textured',
  'tie-dyed',
  'tribal',
  'typography',
  'woven',
]
export const INGREDIENT = [
  'almond',
  'aloe_vera',
  'argan_oil',
  'avocado',
  'beeswax',
  'beetroot',
  'castor_oil',
  'chamomile',
  'charcoal',
  'clay',
  'coconut',
  'eucalyptus',
  'green_tea',
  'honey',
  'jojoba_oil',
  'lemon_grass',
  'moringa',
  'neem',
  'niacinamide',
  'papaya',
  'pomegranate',
  'rose',
  'salicylic_acid',
  'sandalwood',
  'shea_butter',
  'squalene',
  'sunflower',
  'tea_tree',
  'tulsi',
  'turmeric',
  'vitamin_A',
  'vitamin_C',
  'vitamin_E',
]
export const STORAGE_TYPE = ['SSD', 'HDD']
export const COLLAR = [
  'alpha',
  'button down',
  'mandarin',
  'club',
  'spread',
  'slim',
  'peter pan',
  'hood',
  'cutaway',
  'cuban',
  'wingtip',
  'built-up',
]
export const COVERAGE = ['alpha', 'full', 'half', 'medium', 'low', 'sheer']
export const SKIN_TYPE = ['dry', 'oily', 'sensitive', 'normal', 'all', 'very_dry']
export const SPECIAL_FEATURE = ['laser', 'GPS', 'night vision', 'frequency', 'AMOLED screen', 'Dolby audio']
export const FABRIC_FINISH = [
  'alpha',
  'satin',
  'crepe',
  'merserised',
  'printed',
  'painted',
  'embroidered',
  'patchwork',
  'woven',
  'knitted',
]
export const DIAL_SHAPE = [
  'alpha',
  'asymmetric',
  'diamond',
  'oval',
  'rectangle',
  'round',
  'square',
  'triangle',
  'thread',
]
export const BRUSH_TYPE = [
  'foundation',
  'stippling',
  'concealer',
  'powder',
  'blush',
  'contour',
  'bronzer',
  'highlight',
  'eyeshadow',
  'eyeshadow-crease',
  'eyeshadow-blending',
  'eye-liner',
  'mascara',
  'lip',
]
export const FACE_SHAPE = ['alpha', 'rectangular', 'oval', 'circular', 'square', 'triangular']
export const TOP_TYPE = ['jacket', 'shirt', 'sweater', 'sweatshirt', 't-shirt']
export const FRAME_STYLE = ['classic', 'trendy', 'designer', 'nerdy', 'retro', 'sporty']
export const BENEFIT = [
  'age_defying',
  'curling',
  'HD_photogenic',
  'lengthening',
  'luminous',
  'pore_minimising',
  'thickening',
  'volumizing',
  'waterproof',
  'long_lasting',
  'plumping',
  'transfer_proof',
  'transfer_resistant',
  'growth_boosting',
  'cuticle_care',
  'hydrating',
  'strengthening',
  'repairing',
]
export const UNIT = ['MB', 'GB', 'TB']
export const TOE_SHAPE = ['alpha', 'pointed', 'round', 'square']
export const FINISH = [
  'clear',
  'creme',
  'duochrome',
  'gel',
  'glitter',
  'glossy',
  'luminous',
  'matte',
  'metallic',
  'natural',
  'radiant',
  'shimmer',
  'satin',
  'special_effects',
  'tinted',
]
export const WAIST_RISE = ['alpha', 'low', 'high', 'med']
export const TYPE = ['Air Conditioner', 'Refrigerator', 'Vaccum Cleaner', 'Washing Machine']
export const MATERIAL = [
  'alpha',
  'acetate',
  'acrylic',
  'acrylonitrile',
  'aluminium',
  'battery',
  'brass',
  'canvas',
  'carbon',
  'cellulose',
  'cork',
  'cotton',
  'elastane',
  'elastodiene',
  'elastolefin',
  'ethylene',
  'EVA',
  'expanded',
  'faux leather',
  'foamed',
  'glass',
  'grey',
  'iron',
  'jute',
  'leather',
  'linen',
  'lycra',
  'lyocell',
  'mesh',
  'modal',
  'nubuck',
  'nylon',
  'polyamide',
  'polycarbonate',
  'polyester',
  'polyethylene',
  'polymethylpentene',
  'polyoxymethylene',
  'polypropylene',
  'polyurethane',
  'polyvinyl',
  'PU',
  'PVC',
  'rayon',
  'rice',
  'rubber',
  'sand',
  'silicon',
  'silk',
  'stainless',
  'steel',
  'styrene',
  'suede',
  'synthetic',
  'textile',
  'thermo',
  'thermoplastic',
  'tritan',
  'velvet',
  'viscose',
  'water',
  'wood',
  'wool',
  'zinc',
]
export const CLOSURE_TYPE = [
  'alpha',
  'back',
  'button',
  'front',
  'full-zip',
  'half-zip',
  'no-closure',
  'quarter-zip',
  'side',
  'slip-on',
  'tie-up',
]
export const TREND = [
  'alpha',
  'abstract',
  'geometric',
  'nautica',
  'animal',
  'indigo',
  'colour_block',
  'monochrome',
  'typography',
  'tribal',
  'floral',
]
export const SKIN_TONE = ['medium_wheatish', 'fair_light', 'dusky_dark']
export const PREFERENCE = [
  'acetone_free',
  'alcohol_free',
  'allergy_free',
  'ammonia_free',
  'animal_hair',
  'anti_inflammatory',
  'anti_oxidants',
  'clinically_proven',
  'collagen',
  'cruelty_free',
  'dermatologically_tested',
  'formaldehyde_free',
  'fragrance_free',
  'gluten_free',
  'halal_certified',
  'herbal',
  'hyaluronic_acid',
  'hypoallergenic',
  'mineral_oil_free',
  'natural',
  'niacinamide',
  'non_comedogenic',
  'non_vegetarian',
  'nut_free',
  'oil_free',
  'ophthalmologically_tested',
  'organic',
  'paba_free',
  'paraben_free',
  'paraffin_free',
  'petrochemical_free',
  'propleyne_free',
  'pthalate_free',
  'salicylic_acid',
  'silicone_free',
  'sls_free',
  'soap_free',
  'squalane',
  'sulphate_free',
  'sun_protection',
  'synthetic',
  'synthetic_color_free',
  'vegan',
  'vegetarian',
  'vitamin_A',
  'vitamin_C',
  'vitamin_E',
  'water_resistant',
  'waterproof',
  'waterless',
]
export const CONCERN = [
  'acne_blemish',
  'anti_ageing',
  'anti_pollution',
  'bad_breath',
  'blackhead_whitehead',
  'brightening',
  'cavity',
  'chapped_lip',
  'cleansing',
  'colour_protection',
  'cuticle_care',
  'dandruff',
  'dark_spot_pigmentation',
  'dry_frizzy_hair',
  'dryness',
  'dullness',
  'fine_lines_wrinkle',
  'firming',
  'hairfall_thinning',
  'heat_protection',
  'hydration',
  'menstrual_cycle',
  'odour',
  'oil_control',
  'plaque',
  'pores',
  'product_build_up',
  'soap_free',
  'split_end',
  'stretch_mark',
  'sun_protection',
  'tan_removal',
  'tangled_hair',
  'under_eye',
  'uneven_skin_tone',
  'waterproof',
]

const fashion_enum = {
  FOOTWEAR_TYPE,
  LENS_MATERIAL,
  FRAME_TYPE,
  SEASON,
  SPORT_TYPE,
  FASTEN_TYPE,
  FABRIC,
  NECK,
  OCCASION,
  STRAP_MATERIAL,
  FRAME_MATERIAL,
  BUCKLE_MATERIAL,
  FORMULATION,
  FRAME_SIZE,
  FEATURES,
  STONE_TYPE,
  PRINTER_OUTPUT,
  SOCKS_LENGTH,
  GENDER,
  PRESERVATIVE,
  INSOLE,
  HEMLINE,
  GRAIN_TYPE,
  PLATING,
  FLAVOUR,
  DIMENSION_UNIT,
  BRISTLE_TYPE,
  ORNAMENTATION,
  WAIST_BAND,
  FRAGRANCE,
  FRONT_STYLING,
  POWER_TYPE,
  SWEATSHIRT_TYPE,
  CONNECTIVITY,
  PADDING,
  FIT,
  GEM_TYPE,
  CONSCIOUS,
  DISPLAY,
  SEAM,
  BASE_METAL,
  OUTSOLE,
  BUCKLE_TYPE,
  BACKPACK_STYLE,
  UOM,
  JEWELLERY_TYPE,
  MIDSOLE,
  COMPATIBLE_DEVICES,
  SLEEVE_LENGTH,
  BOTTOM_TYPE,
  MATERIAL_FINISH,
  FRAME_SHAPE,
  COLOUR,
  LOCK_TYPE,
  STRAP,
  WASH_TYPE,
  SOLE_MATERIAL,
  HAIR_TYPE,
  SEAM_TYPE,
  PATTERN,
  INGREDIENT,
  STORAGE_TYPE,
  COLLAR,
  COVERAGE,
  SKIN_TYPE,
  SPECIAL_FEATURE,
  FABRIC_FINISH,
  DIAL_SHAPE,
  BRUSH_TYPE,
  FACE_SHAPE,
  TOP_TYPE,
  FRAME_STYLE,
  BENEFIT,
  UNIT,
  TOE_SHAPE,
  FINISH,
  WAIST_RISE,
  TYPE,
  MATERIAL,
  CLOSURE_TYPE,
  TREND,
  SKIN_TONE,
  PREFERENCE,
  CONCERN,
  // ... add the rest of the constants
}

// Export the Enums object
export default fashion_enum
