export const features = {
    "025": "BNP demand signals",
    "022": "BNP promotions planned",
    "015": "Breakup of fulfillment-level taxes in quote",
    "011": "Buyer instructions",
    "00D": "Cancel return request",
    "01E": "Cancellation terms",
    "012": "Cash on delivery order",
    "021": "Catalog as download link",
    "01F": "Codified static terms",
    "00A": "Commercial model for BNP/SNP",
    "014": "Cross-category order flow",
    "018": "Cross-linking make-to-order item in quote trail",
    "016": "Customization of input type text",
    "00C": "Exchange flow",
    "000": "Feature discovery",  
    "005": "Force cancellation",
    "004": "Fulfillment by BNP",
    "020": "Fulfillment delay",
    "024": "Full catalog refresh - search by fulfillment end location",
    "023": "Full catalog refresh - search by item",
    "01C": "Identification of on-network LSP",
    "001": "Item availability",
    "01A": "Item unitized count",
    "01B": "Minimum item quantity",
    "008": "Minimum order value",
    "0092": "Offer buyxgety",
    "0095": "Offer combo",
    "0096": "Offer delivery",
    "0091": "Offer discount",
    "0097": "Offer exchange",
    "0098": "Offer financing",
    "0093": "Offer freebie",
    "0094": "Offer slab",
    "01D": "Options for multi-fulfillment orders",
    "013": "Order price adjustment not tied to return or cancel",
    "0099": "Purchase finance by BNP",
    "00B": "Replacement flow",
    "006": "Return with pickup",
    "002": "Self pickup",
    "017": "Seller creds",
    "003": "Slotted delivery",
    "007": "SNP collecting payment",
    "019": "Streamline fulfillment attributes for hyperlocal",
    "00F": "Update delivery address",
    "010": "Update delivery auth",
    "00E": "Update sale invoice"
  };
  