export default Object.freeze({
  RET_CONTEXT_TTL: 'PT30S',
  RET_CONTEXT_ACTION: 'action',
  DB_PATH: 'dbfiles',
  RET_SEARCH: 'search',
  RET_ONSEARCH: 'on_search',
  RET_ONSEARCHINC: 'on_search_inc',
  RET_SELECT: 'select',
  RET_ONSELECT: 'on_select',
  RET_INIT: 'init',
  RET_ONINIT: 'on_init',
  RET_CONFIRM: 'confirm',
  RET_ONCONFIRM: 'on_confirm',
  RET_TRACK: 'track',
  RET_ONTRACK: 'on_track',
  RET_CANCEL: 'cancel',
  RET_ONCANCEL: 'on_cancel',
  RET_UPDATE: 'update',
  RET_ONUPDATE: 'on_update',
  RET_STATUS: 'status',
  RET_ONSTATUS: 'on_status',
  RET_SUPPORT: 'support',
  RET_ONSUPPORT: 'on_support',
  DECIMAL_PRECISION: 6,
  ORDER_PICKED: 'Order-picked-up',
  ORDER_DELIVERED: 'Order-delivered',
  RET_ISSUE: 'issue',
  RET_ONISSUE: 'on_issue',
  RET_ISSUE_STATUS: 'issue_status',
  RET_ONISSUE_STATUS: 'on_issue_status',
})

export const ApiSequence = {
  SEARCH: 'search_full_catalog_refresh',
  ON_SEARCH: 'on_search_full_catalog_refresh',
  INC_SEARCH: 'search_inc_refresh',
  INC_ONSEARCH: 'on_search_inc_refresh',
  SELECT: 'select',
  ON_SELECT: 'on_select',
  INIT: 'init',
  ON_INIT: 'on_init',
  CONFIRM: 'confirm',
  ON_CONFIRM: 'on_confirm',
  CANCEL: 'cancel',
  ON_CANCEL: 'on_cancel',
  TRACK: 'track',
  ON_TRACK: 'on_track',
  STATUS: 'status',
  ON_STATUS_PENDING: 'on_status_pending',
  ON_STATUS_PICKED: 'on_status_picked',
  ON_STATUS_DELIVERED: 'on_status_delivered',
  UPDATE: 'update',
  ON_UPDATE: 'on_update',
}

export const IGMApiSequence = {
  RET_ISSUE: 'ret_issue',
  RET_ON_ISSUE: 'ret_on_issue',
  RET_ISSUE_STATUS: 'ret_issue_status',
  RET_ON_ISSUE_STATUS: 'ret_on_issue_status',
  LSP_ISSUE: 'lsp_issue',
  LSP_ON_ISSUE: 'lsp_on_issue',
  LSP_ISSUE_STATUS: 'lsp_issue_status',
  LSP_ON_ISSUE_STATUS: 'lsp_on_issue_status',
}

export const actionsArray = [
  'search',
  'on_search',
  'select',
  'on_select',
  'init',
  'on_init',
  'confirm',
  'on_confirm',
  'update',
  'on_update',
  'cancel',
  'on_cancel',
  'track',
  'on_track',
  'status',
  'on_status',
]

export const statusArray = [
  'Pending',
  'Packed',
  'Agent-assigned',
  'Order-picked-up',
  'Out-for-delivery',
  'Order-delivered',
  'Cancelled',
]

export const buyerCancellationRid = new Set(['001', '003', '006', '009', '010'])
