export const VALID_VEHICLE_CATEGORIES = ['METRO']
export const AUTHORIZATION_TYPE = ['QR']
export const AUTHORIZATION_STATUS = ['UNCLAIMED', 'CLAIMED']
export const VALID_DESCRIPTOR_CODES = ['SJT', 'RJT', 'PASS', 'SFSJT']
