export const bap_features: Record<string, string> = {
  '000': 'Catalog processing',
  '001': 'Item availability',
  '002': 'Self-Pickup',
  '003': 'Slotted delivery',
  '004': 'Fulfillment by BNP',
  '005': 'Force cancellation',
  '006': 'Return with pickup',
  '007': 'SNP collecting payment',
  '008': 'Minimum order value',
  '0091': 'Offer (discount)',
  '0092': 'Offer (buyXgetY)',
  '0093': 'Offer (freebie)',
  '0094': 'Offer (slab)',
  '0095': 'Offer (combo)',
  '0096': 'Offer (delivery)',
  '0097': 'Offer (exchange)',
  '0098': 'Offer (financing)',
  '0099': 'Purchase Finance by BNP',
  '00A': 'Commercial model for BNP/SNP',
  '00B': 'Replacement flow',
  '00C': 'Exchange flow',
  '00D': 'Cancel Return Request',
  '00E': 'Update sale invoice',
  '00F': 'Update delivery address',
  '010': 'Update delivery authorization',
  '011': 'Buyer instructions',
  '012': 'Cash on delivery (COD) order',
  '013': 'Order price adjustment',
  '014': 'Cross-category order flow',
  '015': 'Breakup of fulfillment level taxes in quote',
  '016': 'Customization of input type text',
  '017': 'Seller Creds',
  '018': 'Cross-linking make-to-order item in quote_trail',
  '019': 'Streamline fulfillment attributes for hyperlocal',
  '01A': 'Item unitized count',
  '01B': 'Minimum item quantity',
  '01C': 'Identification of on-network LSP',
  '01D': 'Option for multi-fulfillment order',
  '01E': 'Cancellation terms',
  '01F': 'Codified static terms',
  '020': 'Fulfillment delay',
  '021': 'Catalog as download link',
  '022': 'BNP promotions planned',
  '023': 'Full catalog refresh (search by item)',
  '024': 'Full catalog refresh (search by fulfillment end location)',
  '025': 'BNP demand signals',
}
