export const fnbCategories = [
  'Baklava',
  'Bao',
  'Barbecue',
  'Biryani',
  'Bread',
  'Burger',
  'Cakes',
  'Chaat',
  'Cheesecakes',
  'Chicken',
  'Chicken wings',
  'Chips',
  'Coffee',
  'Cookies',
  'Crepes',
  'Dal',
  'Desserts',
  'Dhokla',
  'Dosa',
  'Doughnuts',
  'Eggs',
  'Energy Drinks',
  'Falafel',
  'Fresh Juice',
  'Fries',
  'Ice cream',
  'Idli',
  'Kabab',
  'Kachori',
  'Kulfi',
  'Lassi',
  'Meal bowl',
  'Mezze',
  'Mithai',
  'Momos',
  'Mutton',
  'Nachos',
  'Noodles',
  'Pakodas',
  'Pancakes',
  'Paneer',
  'Pasta',
  'Pastries',
  'Pie',
  'Pizza',
  'Poha',
  'Raita',
  'Rice',
  'Rolls',
  'Roti',
  'Salad',
  'Samosa',
  'Sandwich',
  'Seafood',
  'Shakes & Smoothies',
  'Soft Drink',
  'Soup',
  'Spring Roll',
  'Sushi',
  'Tacos',
  'Tandoori',
  'Tart',
  'Tea',
  'Thali',
  'Tikka',
  'Upma',
  'Uttapam',
  'Vada',
  'Vegetables',
  'Waffle',
  'Wrap',
  'Yogurt',
  'F&B',
]

export const FashionCategories = [
  'Shirts',
  'T Shirts',
  'Sweatshirts',
  'Kurtas & Kurta Sets',
  'Jackets & Coats',
  'Sweaters',
  'Suits',
  'Sherwanis',
  'Track Shirts',
  'Track Suits',
  'Unstitched Fabrics',
  'Dresses',
  'Tops',
  'Trousers',
  'Capris',
  'Coordinates',
  'Playsuits',
  'Jumpsuits',
  'Shrugs & Blouses',
  'Blazers & Waistcoats',
  'Tights, Leggings & Jeggings',
  'Track Pants',
  'Jeans',
  'Shorts',
  'Joggers',
  'Dhotis & Dhoti Pants',
  'Churidars',
  'Salwars',
  'Dungarees & Jumpsuits',
  'Skirts',
  'Clothing Sets',
  'Belts',
  'Caps & Hats',
  'Kurtis, Tunics',
  'Sarees',
  'Ethnic Wear',
  'Palazzos',
  'Dress Materials',
  'Lehenga Cholis',
  'Dupattas & Shawls',
  'Burqas & Hijabs',
  'Blouses',
  'Blouse Pieces',
  'Briefs',
  'Boxers',
  'Vests',
  'Robes',
  'Night Suits',
  'Thermal Wear',
  'Swim Bottoms',
  'Swimwear',
  'Bra',
  'Shapewear',
  'Sleepwear & Loungewear',
  'Camisoles',
  'Lingerie Sets & Accessories',
  'Bath Robes',
  'Towels',
  'Pyjamas',
  'Party Wear',
  'Innerwear & Sleepwear',
  'Nightwear & Loungewear',
  'Watches',
  'Gloves',
  'Socks',
  'Stockings',
  'Laces',
  'Soles & Charms',
  'Shoe Racks & Organisers',
  'Shoe Care - Accessories',
  'Flip-Flops & Flats',
  'Sandals & Floaters',
  'Backpacks',
  'Handbags',
  'Trolley, Luggage & Suitcases',
  'Formal Shoes',
  'Casual Shoes',
  'Sports Shoes',
  'Outdoor Shoes',
  'Work & Safety Shoes',
  'Ethnic Shoes',
  'Boots',
  'Heels',
  'Contact Lenses',
  'Eye Glasses',
  'Eye Glass Frames',
  'Sunglasses',
  'Contact Lens Cases',
  'Contact Lens Solutions',
  'Contact Lens Tweezers',
  'Eyeglasses Pouches & Cases',
  'Microfiber Wipes',
  'Eyewear Slings',
  'Bracelets',
  'Chains',
  'Mangalsutra',
  'Anklets',
  'Bangles & Bracelets',
  'Necklaces',
  'Earrings',
  'Jewellery Sets',
  'Nosepins & Noserings',
  'Pendants',
  'Rings',
  'Toe Rings',
  'Gold Coins',
  'Brooch',
  'Fashion',
]

export const groceryCategories = [
  'Fruits and Vegetables',
  'Masala & Seasoning',
  'Oil & Ghee',
  'Eggs, Meat & Fish',
  'Cleaning & Household',
  'Bakery, Cakes & Dairy',
  'Pet Care',
  'Stationery',
  'Dairy and Cheese',
  'Snacks, Dry Fruits, Nuts',
  'Pasta, Soup and Noodles',
  'Cereals and Breakfast',
  'Sauces, Spreads and Dips',
  'Chocolates and Biscuits',
  'Cooking and Baking Needs',
  'Tinned and Processed Food',
  'Atta, Flours and Sooji',
  'Rice and Rice Products',
  'Dals and Pulses',
  'Salt, Sugar and Jaggery',
  'Energy and Soft Drinks',
  'Water',
  'Tea and Coffee',
  'Fruit Juices and Fruit Drinks',
  'Snacks and Namkeen',
  'Ready to Cook and Eat',
  'Pickles and Chutney',
  'Indian Sweets',
  'Frozen Vegetables',
  'Frozen Snacks',
  'Gift Voucher',
  'Grocery',
]

export const beautyCategories = [
  'Fragrance',
  'Bath Soaps and Gels',
  'Hair Oils, Care, and Styling',
  'Shampoos and Conditioners',
  'Shaving and Grooming',
  'Beard Care and Tools',
  'Grooming Tools and Accessories',
  'Makeup - Nail Care',
  'Makeup - Eyes',
  'Makeup - Face',
  'Makeup - Lips',
  'Makeup - Body',
  'Makeup - Remover',
  'Makeup - Sets and Kits',
  'Makeup - Tools and Brushes',
  'Makeup - Kits and Combos',
  'Skin Care - Face Cleansers',
  'Skin Care - Hand and Feet',
  'Body Care - Cleansers',
  'Body Care - Moisturizers',
  'Body Care - Loofah and Other Tools',
  'Body Care - Bath Salt and Additives',
  'Hair Care - Shampoo, Oils, Conditioners',
  'Skin Care - Lotions, Moisturisers, and Creams',
  'Skin Care - Oils and Serums',
  'Gift Voucher',
  'BPC',
]

export const electronicsCategories = [
  'Mobile Phone',
  'Smart Watch',
  'Headset',
  'Laptop',
  'Desktop',
  'Tablet',
  'Keyboard',
  'Monitor',
  'Mouse',
  'Power Bank',
  'Earphone',
  'True Wireless Stereo (TWS)',
  'Adapter',
  'Cable',
  'Extension Cord',
  'Audio Accessories',
  'Home Audio',
  'Microphone',
  'Speaker',
  'Vehicle Audio',
  'Camcorder',
  'Camera',
  'Camera Bag',
  'Batteries',
  'Charger',
  'Camera Lens',
  'Photo Printer',
  'Tripod',
  'Camera Accessories',
  'UPS',
  'Networking Device',
  'Printer',
  'Printer Accessories',
  'Storage Drive',
  'Pen Drive',
  'Memory Card',
  'Computer Component',
  'Cooling Pad',
  'Docking Station',
  'Keyboard Guard',
  'Laptop Skin',
  'Laptop Stand',
  'Mousepad',
  'Laptop Bag',
  'Screen Protector',
  'Computer Accessories',
  'Computer Software',
  'Ebook Reader',
  'Tablet Accessories',
  'Gaming Controller',
  'Gaming Chair',
  'Gaming Accessories',
  'Gaming Console',
  'Video Games',
  'Mobile Cover',
  'Mobile Mount',
  'Mobile Screen Guard',
  'Selfie Stick',
  'Mobile Skin Sticker',
  'Biometrics',
  'Home Alarm',
  'Home Automation',
  'Smart Switch',
  'Smart Lighting',
  'Home Safe',
  'Intercom',
  'Sensor',
  'Smart TV',
  'Standard TV',
  'TV Mount',
  'Remote',
  'Streaming Device',
  'TV Accessories',
  'Virtual Reality Headset',
  '3D Glasses',
  '3D Modulator',
  'Projector',
  'Projector Screen',
  'Projector Mount',
  'Projector Accessories',
  'TV Part',
  'TV Remote',
  'Set Top Box',
  'TV Stand',
  'Video Player',
  'Digital Photo Frame',
  'Home Theatre Projector',
  'Video Player Accessories',
  'Smart Band',
  'Smart Glasses',
  'Watch Strap Band',
  'Wearable Accessories',
  'Electronics',
]

export const appliancesCategories = [
  'Air Purifier',
  'Dehumidifier',
  'Humidifier',
  'Air Cleaner Accessories',
  'Air Conditioner',
  'Air Conditioner Accessories',
  'Air Cooler',
  'Trimmer',
  'Shaver',
  'Epilator',
  'Hair Straightener',
  'Hair Dryer',
  'Hair Curler',
  'Hair Crimper',
  'Electric Brush',
  'Electric Iron',
  'Electric Sewing Machine',
  'Water Heater',
  'Heater Cables',
  'Air Heater',
  'Coffee Maker',
  'Beverage Maker',
  'Roti Maker',
  'Induction Cooktop',
  'Sandwich Maker',
  'Electric Cooker',
  'Electric Kettle',
  'Microwave Oven',
  'OTG',
  'Toaster',
  'Electric Air Fryer',
  'Cooking Appliance Accessories',
  'Coffee Grinder',
  'Food Processor',
  'Pasta Maker',
  'Food Processor Accessories',
  'Blender',
  'Juicer',
  'Mixer Grinder',
  'Wet Grinder',
  'Dishwasher',
  'Dishwasher Accessories',
  'Electric Chimney',
  'Kitchen Accessories',
  'Freezer',
  'Refrigerator',
  'Refrigerator Accessories',
  'Vacuum Cleaner',
  'Vacuum Cleaner Parts and Accessories',
  'Washing Machine',
  'Washing Machine Accessories',
  'Water Purifier',
  'Water Cooler',
  'Water Dispenser',
  'Water Purifier Service Kit',
  'Water Purifier Filter',
  'Water Purifier Candle',
  'Water Purifier Pipe',
  'Water Purifier Accessories',
  'Water Cooler Accessories',
  'Inverter',
  'Inverter Batteries',
  'Battery tray',
  'Voltage Stabilizer',
  'Appliances',
]

export const homeCategories = [
  'Home Decor',
  'Furniture',
  'Home Furnishing - Bedding and Linen',
  'Cleaning Supplies',
  'Electricals',
  'Bathroom and Kitchen fixtures',
  'Garden & Outdoor',
  'Sports and Fitness Equipment',
  'Cookware',
  'Serveware',
  'Kitchen Storage and Containers',
  'Kitchen Tools',
  'Closet/Laundry/Shoe Organization',
  'Toys and Games',
  'Stationery',
  'Gift Voucher',
  'Home & Kitchen',
  'Bins and Bathroom',
  'Disposables and Garbage Bags',
  'Fresheners and Repellents',
  'Mops, Brushes and Scrubs',
  'Party and Festive Needs',
  'Flowers',
  'Pooja Needs',
  'Car and Shoe Care',
]

export const healthCategories = [
  'Pain Relief',
  'Nutrition and Fitness Supplements',
  'Speciality Care',
  'Covid Essentials',
  'Diabetes Control',
  'Healthcare & Fitness Devices',
  'Ayurvedic',
  'Homeopathy',
  'Unani and Siddha',
  'Elder Care',
  'Baby Care',
  'Orthopaedic Care',
  'Mobility Aids',
  'Medicated Hair Care',
  'Medicated Skin Care',
  'Speciality Face Cleansers',
  'Gastric Care',
  'ENT Care',
  'Eye Care',
  'Cold and Cough',
  'Sexual Wellness',
  'Feminine Care',
  'Maternity Care',
  'Nursing and Feeding',
  'Hand Wash',
  'Sanitizers',
  'Baby Care - Wipes and Buds',
  'Baby Care - Rash Creams',
  'Baby Care - Diapers and Accessories',
  'Health and Safety',
  'Oral Care',
  'Contraceptives',
  'Breathe Easy',
  'Health Foods and Drinks',
  'Wound Care and Dressings',
  'Surgicals',
  'Mental Wellness',
  'Gift Voucher',
  'Health & Wellness',
]
export const agriCategories = [
  'Seed',
  'Pesticide',
  'Fertilizer',
  'Organic Crop Protection',
  'Organic Crop Nutrition',
  'Tools and Machinery',
  'Cattle Feed',
]
export const automobileCategories = [
  'Gaskets & Valves',
  'Automotive Belts & Pulleys',
  'Radiators, Pumps & Elbow Components',
  'Filters',
  'Bearings',
  'Clutches',
  'Engine Cooling',
  'Oils & Lubricants',
  'Mounting',
  'AC & Components',
  'Kit & Engine Components',
  'Suspension Parts & Rubber Kits',
  'Steering Parts & Components',
  'Brake Parts',
  'Tyres, Rims & Alloys',
  'Interior Accessories & Care',
  'Exterior Accessories & Care',
  'Paintwork, Tools & Accessories',
  'Styling Comforts',
  'Vehicle Storage',
  'Vehicle Tools',
  'Security & Cameras',
  'Electric Parts & Components',
  'Plugs, Switches & Ignitions',
  'Lights',
  'Sensors',
  'Navigation Devices',
  'Vehicle Electronics & Accessories',
  'Battery & Accessories',
  'Exhaust Systems',
  'Auto Body Parts & Mirrors',
  'Windscreen',
  'Bike Safety & Accessories',
  'Helmets',
  'Special Apparel',
  'Glasses & Eyewear',
  'Gloves',
  'T-shirts & Tops',
  'Jackets',
  'Protective Wear & Guards',
  'Eyewear',
  'Gifts & Merchandise',
  'Backpacks & Bags',
  'Badges & Emblems',
  'Gift Sets',
  'Key Rings',
  'Lighters',
  'Patches',
  'Model Vehicles',
  'Signs',
  'Service, Labour Charges',
  'Cycle',
  'Scooter',
  'Motorcycle',
  'Electric Bikes',
  'Electric Scooters',
  'Electric Cycle',
  'Scooty',
  'Mopeds',
  'Three Wheeler',
  'Sedan',
  'Convertible',
  'Coupe',
  'Station Wagon',
  'Hatchback',
  'Crossover',
  'Van',
  'MUV',
  'SUV',
  'Truck',
  'Luxury SUV',
  'Luxury Hatchback',
  'Luxury Sedan',
  'Sports Vehicle',
  'Golf Cart',
  'Carriage',
  'Bus',
  'Agricultural Vehicles',
  'Motorhomes',
  'Vehicle Rental'
];
export const combinedCategory = [
  ...new Set([
    ...beautyCategories,
    ...electronicsCategories,
    ...FashionCategories,
    ...appliancesCategories,
    ...groceryCategories,
    ...homeCategories,
    ...healthCategories,
    ...agriCategories,
    ...automobileCategories
  ]),
]

export const retailPymntTtl = {
  'delivery charges': 'delivery',
  'packing charges': 'packing',
  tax: 'tax',
  discount: 'discount',
  'convenience fee': 'misc',
}

export const taxNotInlcusive = [...fnbCategories]

export const groceryStatutory = [
  {
    'category id': 'Fruits and Vegetables',
    'Protocol key mapping': null,
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Masala & Seasoning',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Oil & Ghee',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Gourmet & World Foods',
    'Protocol key mapping': '@ondc/org/statutory_reqs_prepackaged_food',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Foodgrains',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Eggs, Meat & Fish',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Cleaning & Household',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Beverages',
    'Protocol key mapping': '@ondc/org/statutory_reqs_prepackaged_food',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Beauty & Hygiene',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Bakery, Cakes & Dairy',
    'Protocol key mapping': '@ondc/org/statutory_reqs_prepackaged_food',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Kitchen Accessories',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Baby Care',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Snacks & Branded Foods',
    'Protocol key mapping': '@ondc/org/statutory_reqs_prepackaged_food',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Pet Care',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
  {
    'category id': 'Stationery',
    'Protocol key mapping': '@ondc/org/statutory_reqs_packaged_commodities',
    parent_category_id: 'Grocery',
  },
]

export enum DOMAIN {
  RET10 = 'RET10',
  RET11 = 'RET11',
  RET12 = 'RET12',
  RET13 = 'RET13',
  RET14 = 'RET14',
  RET15 = 'RET15',
  RET16 = 'RET16',
  RET17 = 'RET17',
  RET18 = 'RET18',
  RET19 = 'RET19',
  AGR10 = 'AGR10',
  RET1A = 'RET1A'
}

export enum FLOW {
  FLOW1 = '1',
  FLOW2 = '2',
  FLOW3 = '3',
  FLOW4 = '4',
  FLOW5 = '5',
  FLOW6 = '6',
  FLOW7 = '7',
  FLOW8 = '8',
  FLOW9 = '9',
}

export enum statutory_reqs {
  PrepackagedFood = '@ondc/org/statutory_reqs_prepackaged_food',
  PackagedCommodities = '@ondc/org/statutory_reqs_packaged_commodities',
  None = 'None'
}